INSERT INTO game_klassiker_questions (fk_pool, content, content_english) VALUES
("22", "Wer ist der/die mutigste?", "Who is the bravest?"),
("22", "Wer macht die besten Witze?", "Who makes the best jokes?"),
("22", "Wer würde am ehesten eine Bank ausrauben?", "Who would most likely rob a bank?"),
("22", "Wer ist der/die hilfsbereiteste?", "Who is the most helpful?"),
("22", "Wer kocht am besten?", "Who cooks the best?"),
("22", "Wer wird am ehesten Präsident/in?", "Who is most likely to become president?"),
("22", "Wer ist der/die ordentlichste?", "Who is the tidiest?"),
("22", "Wer feiert die wildesten Partys?", "Who throws the wildest parties?"),
("22", "Wer würde am ehesten einen Fallschirmsprung machen?", "Who would most likely go skydiving?"),
("22", "Wer ist der/die lustigste?", "Who is the funniest?"),
("22", "Wer macht die schlechtesten Witze?", "Who makes the worst jokes?"),
("22", "Wer wird am ehesten einen Bestseller schreiben?", "Who is most likely to write a bestseller?"),
("22", "Wer ist der/die kreativste?", "Who is the most creative?"),
("22", "Wer treibt am meisten Sport?", "Who does the most sports?"),
("22", "Wer würde am ehesten ein Haus bauen?", "Who is most likely to build a house?"),
("22", "Wer ist der/die intelligenteste?", "Who is the smartest?"),
("22", "Wer hat die meisten Hobbys?", "Who has the most hobbies?"),
("22", "Wer wird am ehesten einen Nobelpreis gewinnen?", "Who is most likely to win a Nobel Prize?"),
("22", "Wer ist der/die chaotischste?", "Who is the most chaotic?"),
("22", "Wer kocht am schlechtesten?", "Who cooks the worst?"),
("22", "Wer würde am ehesten auswandern?", "Who is most likely to emigrate?"),
("22", "Wer ist der/die empathischste?", "Who is the most empathetic?"),
("22", "Wer macht die meisten Reisen?", "Who travels the most?"),
("22", "Wer wird am ehesten reich werden?", "Who is most likely to become rich?"),
("22", "Wer ist der/die pünktlichste?", "Who is the most punctual?"),
("22", "Wer liest am meisten?", "Who reads the most?"),
("22", "Wer würde am ehesten in einer Reality-Show mitmachen?", "Who is most likely to participate in a reality show?"),
("22", "Wer ist der/die abenteuerlustigste?", "Who is the most adventurous?"),
("22", "Wer macht die besten Fotos?", "Who takes the best photos?"),
("22", "Wer wird am ehesten berühmt werden?", "Who is most likely to become famous?"),
("22", "Wer ist der/die großzügigste?", "Who is the most generous?"),
("22", "Wer hat das beste Modebewusstsein?", "Who has the best fashion sense?"),
("22", "Wer würde am ehesten in einem Horrorfilm überleben?", "Who is most likely to survive a horror movie?"),
("22", "Wer ist der/die ehrlichste?", "Who is the most honest?"),
("22", "Wer verbringt die meiste Zeit am Handy?", "Who spends the most time on their phone?"),
("22", "Wer wird am ehesten ein Unternehmen gründen?", "Who is most likely to start a business?"),
("22", "Wer ist der/die sportlichste?", "Who is the most athletic?"),
("22", "Wer arbeitet am härtesten?", "Who works the hardest?"),
("22", "Wer wird am ehesten ein/e berühmte/r Künstler/in?", "Who is most likely to become a famous artist?"),
("22", "Wer ist der/die spontanste?", "Who is the most spontaneous?"),
("22", "Wer verbringt die meiste Zeit vor dem Spiegel?", "Who spends the most time in front of the mirror?"),
("22", "Wer würde am ehesten in der Wildnis überleben?", "Who is most likely to survive in the wild?"),
("22", "Wer ist der/die risikofreudigste?", "Who is the most risk-taking?"),
("22", "Wer schaut die meisten Filme?", "Who watches the most movies?"),
("22", "Wer wird am ehesten einen Weltrekord aufstellen?", "Who is most likely to set a world record?"),
("22", "Wer ist der/die selbstbewussteste?", "Who is the most confident?"),
("22", "Wer hat die meisten Haustiere?", "Who has the most pets?"),
("22", "Wer wird am ehesten ein Buch schreiben?", "Who is most likely to write a book?"),
("22", "Wer ist der/die ruhigste?", "Who is the calmest?"),
("22", "Wer spricht die meisten Sprachen?", "Who speaks the most languages?"),
("22", "Wer würde am ehesten in einem Science-Fiction-Film mitspielen?", "Who is most likely to star in a sci-fi movie?"),
("22", "Wer ist der/die motivierteste?", "Who is the most motivated?"),
("22", "Wer hat die meisten Freunde?", "Who has the most friends?"),
("22", "Wer wird am ehesten ein Musikalbum aufnehmen?", "Who is most likely to record a music album?"),
("22", "Wer ist der/die entspannteste?", "Who is the most relaxed?"),
("22", "Wer verbringt die meiste Zeit mit Videospielen?", "Who spends the most time playing video games?"),
("22", "Wer würde am ehesten eine neue Sportart ausprobieren?", "Who is most likely to try a new sport?"),
("22", "Wer ist der/die ehrgeizigste?", "Who is the most ambitious?"),
("22", "Wer gibt das meiste Geld für Kleidung aus?", "Who spends the most money on clothes?"),
("22", "Wer wird am ehesten Politiker/in?", "Who is most likely to become a politician?"),
("22", "Wer ist der/die ruhigste?", "Who is the calmest?"),
("22", "Wer hat die meisten Geschwister?", "Who has the most siblings?"),
("22", "Wer würde am ehesten bei einem Marathon mitlaufen?", "Who is most likely to run a marathon?"),
("22", "Wer ist der/die spontanste?", "Who is the most spontaneous?"),
("22", "Wer verbringt die meiste Zeit am Computer?", "Who spends the most time on the computer?"),
("22", "Wer wird am ehesten Wissenschaftler/in?", "Who is most likely to become a scientist?"),
("22", "Wer ist der/die disziplinierteste?", "Who is the most disciplined?"),
("22", "Wer isst am meisten Fast Food?", "Who eats the most fast food?"),
("22", "Wer würde am ehesten einen Roadtrip machen?", "Who is most likely to go on a road trip?"),
("22", "Wer ist der/die neugierigste?", "Who is the most curious?"),
("22", "Wer liest die meisten Bücher?", "Who reads the most books?"),
("22", "Wer wird am ehesten ein Restaurant eröffnen?", "Who is most likely to open a restaurant?"),
("22", "Wer ist der/die ungeduldigste?", "Who is the most impatient?"),
("22", "Wer hat die meisten Tattoos?", "Who has the most tattoos?"),
("22", "Wer würde am ehesten eine Weltreise machen?", "Who is most likely to go on a world tour?"),
("22", "Wer ist der/die humorvollste?", "Who is the most humorous?"),
("22", "Wer macht die meisten Selfies?", "Who takes the most selfies?"),
("22", "Wer wird am ehesten Lehrer/in?", "Who is most likely to become a teacher?"),
("22", "Wer ist der/die abenteuerlustigste?", "Who is the most adventurous?"),
("22", "Wer hat die meisten sozialen Medien?", "Who has the most social media accounts?"),
("22", "Wer würde am ehesten in einem anderen Land leben?", "Who is most likely to live in another country?"),
("22", "Wer ist der/die geduldigste?", "Who is the most patient?"),
("22", "Wer verbringt die meiste Zeit mit Schlafen?", "Who spends the most time sleeping?"),
("22", "Wer wird am ehesten Schauspieler/in?", "Who is most likely to become an actor?"),
("22", "Wer ist der/die kommunikativste?", "Who is the most communicative?"),
("22", "Wer trinkt am meisten Kaffee?", "Who drinks the most coffee?"),
("22", "Wer würde am ehesten ein Tattoo stechen lassen?", "Who is most likely to get a tattoo?"),
("22", "Wer ist der/die empathischste?", "Who is the most empathetic?"),
("22", "Wer schaut die meisten TV-Serien?", "Who watches the most TV shows?"),
("22", "Wer wird am ehesten Pilot/in?", "Who is most likely to become a pilot?"),
("22", "Wer ist der/die neugierigste?", "Who is the most curious?"),
("22", "Wer gibt das meiste Geld für Technik aus?", "Who spends the most money on technology?"),
("22", "Wer würde am ehesten ein neues Hobby anfangen?", "Who is most likely to start a new hobby?"),
("22", "Wer ist der/die redseligste?", "Who is the most talkative?"),
("22", "Wer hat die größte Filmsammlung?", "Who has the largest movie collection?"),
("22", "Wer wird am ehesten ein YouTube-Star?", "Who is most likely to become a YouTube star?"),
("22", "Wer ist der/die toleranteste?", "Who is the most tolerant?"),
("22", "Wer hat die meisten Paar Schuhe?", "Who has the most pairs of shoes?"),
("22", "Wer würde am ehesten ein Haustier adoptieren?", "Who is most likely to adopt a pet?"),
("22", "Wer ist der/die wissbegierigste?", "Who is the most eager to learn?"),
("22", "Wer gibt das meiste Geld für Bücher aus?", "Who spends the most money on books?"),
("22", "Wer wird am ehesten ein Strandhaus kaufen?", "Who is most likely to buy a beach house?");
