INSERT INTO game_klassiker_questions (fk_pool, content, content_english) VALUES
("22", "Wer ist der/die mutigste?", "Who is the bravest?"),
("22", "Wer macht die besten Witze?", "Who tells the best jokes?"),
("22", "Wer würde am ehesten eine Weltreise machen?", "Who is most likely to go on a world tour?"),
("22", "Wer ist der größte Schisser?", "Who is the biggest coward?"),
("22", "Wer macht am meisten Sport?", "Who exercises the most?"),
("22", "Wer würde am ehesten auswandern?", "Who is most likely to emigrate?"),
("22", "Wer ist am kreativsten?", "Who is the most creative?"),
("22", "Wer kocht am besten?", "Who cooks the best?"),
("22", "Wer würde am ehesten in einem Horrorfilm überleben?", "Who is most likely to survive in a horror movie?"),
("22", "Wer ist am ordentlichsten?", "Who is the most orderly?"),
("22", "Wer trinkt am meisten Kaffee?", "Who drinks the most coffee?"),
("22", "Wer würde am ehesten ein Buch schreiben?", "Who is most likely to write a book?"),
("22", "Wer ist am empathischsten?", "Who is the most empathetic?"),
("22", "Wer schläft am längsten?", "Who sleeps the longest?"),
("22", "Wer würde am ehesten ein Geheimnis für immer bewahren?", "Who is most likely to keep a secret forever?"),
("22", "Wer ist der/die sportlichste?", "Who is the most athletic?"),
("22", "Wer verbringt die meiste Zeit auf Social Media?", "Who spends the most time on social media?"),
("22", "Wer würde am ehesten einen Song schreiben?", "Who is most likely to write a song?"),
("22", "Wer ist am zielstrebigsten?", "Who is the most determined?"),
("22", "Wer isst am meisten Fast Food?", "Who eats the most fast food?"),
("22", "Wer würde am ehesten eine Wohltätigkeitsorganisation gründen?", "Who is most likely to start a charity?"),
("22", "Wer ist der/die intelligenteste?", "Who is the smartest?"),
("22", "Wer reist am meisten?", "Who travels the most?"),
("22", "Wer würde am ehesten Präsident/in werden?", "Who is most likely to become president?"),
("22", "Wer ist am humorvollsten?", "Who has the best sense of humor?"),
("22", "Wer verbringt die meiste Zeit mit Videospielen?", "Who spends the most time playing video games?"),
("22", "Wer würde am ehesten in einer Reality-Show mitmachen?", "Who is most likely to participate in a reality show?"),
("22", "Wer ist am organisiertesten?", "Who is the most organized?"),
("22", "Wer liest am meisten Bücher?", "Who reads the most books?"),
("22", "Wer würde am ehesten einen Marathon laufen?", "Who is most likely to run a marathon?"),
("22", "Wer ist am spontansten?", "Who is the most spontaneous?"),
("22", "Wer schaut am meisten Fernsehen?", "Who watches the most TV?"),
("22", "Wer würde am ehesten einen Extremsport ausprobieren?", "Who is most likely to try an extreme sport?"),
("22", "Wer ist am geselligsten?", "Who is the most sociable?"),
("22", "Wer isst am langsamsten?", "Who eats the slowest?"),
("22", "Wer würde am ehesten ein eigenes Geschäft eröffnen?", "Who is most likely to start their own business?"),
("22", "Wer ist am geduldigsten?", "Who is the most patient?"),
("22", "Wer telefoniert am längsten?", "Who talks on the phone the longest?"),
("22", "Wer würde am ehesten ein Kunstwerk erschaffen?", "Who is most likely to create a piece of art?"),
("22", "Wer ist der größte Morgenmuffel?", "Who is the biggest grump in the morning?"),
("22", "Wer arbeitet am meisten?", "Who works the most?"),
("22", "Wer würde am ehesten eine wissenschaftliche Entdeckung machen?", "Who is most likely to make a scientific discovery?"),
("22", "Wer ist der/die musikalischste?", "Who is the most musical?"),
("22", "Wer redet am meisten?", "Who talks the most?"),
("22", "Wer würde am ehesten bei einem Quiz gewinnen?", "Who is most likely to win a quiz?"),
("22", "Wer ist der größte Pessimist?", "Who is the biggest pessimist?"),
("22", "Wer schläft am wenigsten?", "Who sleeps the least?"),
("22", "Wer würde am ehesten einen Weltrekord aufstellen?", "Who is most likely to set a world record?"),
("22", "Wer ist der/die ordentlichste?", "Who is the tidiest?"),
("22", "Wer geht am häufigsten ins Kino?", "Who goes to the cinema the most?"),
("22", "Wer würde am ehesten ein Museum eröffnen?", "Who is most likely to open a museum?"),
("22", "Wer ist der größte Optimist?", "Who is the biggest optimist?"),
("22", "Wer gibt am meisten Geld aus?", "Who spends the most money?"),
("22", "Wer würde am ehesten eine Rede vor einem großen Publikum halten?", "Who is most likely to give a speech to a large audience?"),
("22", "Wer ist der/die chaotischste?", "Who is the most chaotic?"),
("22", "Wer kauft die meisten Bücher?", "Who buys the most books?"),
("22", "Wer würde am ehesten bei einem Talentwettbewerb gewinnen?", "Who is most likely to win a talent competition?"),
("22", "Wer ist der/die witzigste?", "Who is the funniest?"),
("22", "Wer isst am meisten Gemüse?", "Who eats the most vegetables?"),
("22", "Wer würde am ehesten ein Rätsel lösen?", "Who is most likely to solve a puzzle?"),
("22", "Wer ist am hilfsbereitesten?", "Who is the most helpful?"),
("22", "Wer bleibt am längsten wach?", "Who stays up the latest?"),
("22", "Wer würde am ehesten ein neues Hobby beginnen?", "Who is most likely to start a new hobby?"),
("22", "Wer ist am freundlichsten?", "Who is the friendliest?"),
("22", "Wer spricht am meisten Fremdsprachen?", "Who speaks the most foreign languages?"),
("22", "Wer würde am ehesten eine fremde Kultur erkunden?", "Who is most likely to explore a foreign culture?"),
("22", "Wer ist der größte Träumer?", "Who is the biggest dreamer?"),
("22", "Wer benutzt am häufigsten soziale Medien?", "Who uses social media the most?"),
("22", "Wer würde am ehesten in die Politik gehen?", "Who is most likely to go into politics?"),
("22", "Wer ist der/die diplomatischste?", "Who is the most diplomatic?"),
("22", "Wer liebt am meisten Tiere?", "Who loves animals the most?"),
("22", "Wer würde am ehesten einen Film drehen?", "Who is most likely to make a movie?"),
("22", "Wer ist der/die ehrlichste?", "Who is the most honest?"),
("22", "Wer verbringt die meiste Zeit draußen?", "Who spends the most time outdoors?"),
("22", "Wer würde am ehesten eine neue Sprache lernen?", "Who is most likely to learn a new language?"),
("22", "Wer ist der/die treueste?", "Who is the most loyal?"),
("22", "Wer vergisst am häufigsten Dinge?", "Who forgets things the most?"),
("22", "Wer würde am ehesten einen Schatz finden?", "Who is most likely to find a treasure?"),
("22", "Wer ist der/die höflichste?", "Who is the most polite?"),
("22", "Wer isst am schnellsten?", "Who eats the fastest?"),
("22", "Wer würde am ehesten eine lange Reise unternehmen?", "Who is most likely to take a long journey?"),
("22", "Wer ist der/die romantischste?", "Who is the most romantic?"),
("22", "Wer schaut am meisten Filme?", "Who watches the most movies?"),
("22", "Wer würde am ehesten ein wissenschaftliches Experiment durchführen?", "Who is most likely to conduct a scientific experiment?"),
("22", "Wer ist der größte Abenteurer?", "Who is the biggest adventurer?"),
("22", "Wer isst am liebsten Süßigkeiten?", "Who loves sweets the most?"),
("22", "Wer würde am ehesten ein neues Rezept ausprobieren?", "Who is most likely to try a new recipe?"),
("22", "Wer ist der/die ruhigste?", "Who is the calmest?"),
("22", "Wer verbringt am meisten Zeit mit seiner Familie?", "Who spends the most time with their family?"),
("22", "Wer würde am ehesten einen Freund für immer behalten?", "Who is most likely to keep a friend forever?"),
("22", "Wer ist der größte Spaßvogel?", "Who is the biggest joker?"),
("22", "Wer trinkt am meisten Tee?", "Who drinks the most tea?"),
("22", "Wer würde am ehesten ein eigenes Restaurant eröffnen?", "Who is most likely to open their own restaurant?"),
("22", "Wer ist der größte Tagträumer?", "Who is the biggest daydreamer?"),
("22", "Wer liest am meisten Nachrichten?", "Who reads the most news?"),
("22", "Wer würde am ehesten ein technisches Gerät reparieren?", "Who is most likely to repair a technical device?"),
("22", "Wer ist der größte Workaholic?", "Who is the biggest workaholic?"),
("22", "Wer isst am meisten Schokolade?", "Who eats the most chocolate?"),
("22", "Wer würde am ehesten eine neue Sportart ausprobieren?", "Who is most likely to try a new sport?"),
("22", "Wer ist am modischsten?", "Who is the most fashionable?"),
("22", "Wer liebt am meisten Kunst?", "Who loves art the most?"),
("22", "Wer würde am ehesten ein Start-up gründen?", "Who is most likely to start a start-up?"),
("22", "Wer ist der/die verantwortungsvollste?", "Who is the most responsible?"),
("22", "Wer tanzt am besten?", "Who dances the best?"),
("22", "Wer würde am ehesten ein Rätsel lösen?", "Who is most likely to solve a riddle?"),
("22", "Wer ist der/die abenteuerlustigste?", "Who is the most adventurous?"),
("22", "Wer isst am meisten Obst?", "Who eats the most fruit?"),
("22", "Wer würde am ehesten auf dem Mond landen?", "Who is most likely to land on the moon?"),
("22", "Wer ist der größte Denker?", "Who is the biggest thinker?"),
("22", "Wer geht am häufigsten ins Fitnessstudio?", "Who goes to the gym the most?"),
("22", "Wer würde am ehesten ein berühmter Musiker werden?", "Who is most likely to become a famous musician?"),
("22", "Wer ist der größte Realist?", "Who is the biggest realist?"),
("22", "Wer verbringt die meiste Zeit mit Lesen?", "Who spends the most time reading?"),
("22", "Wer würde am ehesten eine lange Wanderung machen?", "Who is most likely to go on a long hike?"),
("22", "Wer ist der größte Perfektionist?", "Who is the biggest perfectionist?"),
("22", "Wer fährt am liebsten Fahrrad?", "Who likes cycling the most?"),
("22", "Wer würde am ehesten ein eigenes Kleidungslabel gründen?", "Who is most likely to start their own clothing label?"),
("22", "Wer ist der/die rücksichtsvollste?", "Who is the most considerate?"),
("22", "Wer kann am besten singen?", "Who can sing the best?"),
("22", "Wer würde am ehesten eine Stadtführung geben?", "Who is most likely to give a city tour?"),
("22", "Wer ist der größte Planer?", "Who is the biggest planner?"),
("22", "Wer isst am meisten Fleisch?", "Who eats the most meat?"),
("22", "Wer würde am ehesten in einer Band spielen?", "Who is most likely to play in a band?"),
("22", "Wer ist am höflichsten?", "Who is the most polite?"),
("22", "Wer liebt am meisten Musik?", "Who loves music the most?"),
("22", "Wer würde am ehesten eine neue Sportart erlernen?", "Who is most likely to learn a new sport?"),
("22", "Wer ist der größte Tierfreund?", "Who is the biggest animal lover?"),
("22", "Wer verbringt die meiste Zeit mit Freunden?", "Who spends the most time with friends?"),
("22", "Wer würde am ehesten einen Marathon laufen?", "Who is most likely to run a marathon?"),
("22", "Wer ist der größte Skeptiker?", "Who is the biggest skeptic?"),
("22", "Wer trinkt am meisten Wasser?", "Who drinks the most water?"),
("22", "Wer würde am ehesten einen Tanzwettbewerb gewinnen?", "Who is most likely to win a dance competition?"),
("22", "Wer ist der/die selbstbewussteste?", "Who is the most confident?"),
("22", "Wer verbringt die meiste Zeit am Strand?", "Who spends the most time at the beach?"),
("22", "Wer würde am ehesten eine neue Technologie entwickeln?", "Who is most likely to develop a new technology?"),
("22", "Wer ist der/die abenteuerlustigste?", "Who is the most adventurous?"),
("22", "Wer liebt am meisten Mode?", "Who loves fashion the most?"),
("22", "Wer würde am ehesten in einem anderen Land leben?", "Who is most likely to live in another country?"),
("22", "Wer ist der größte Träumer?", "Who is the biggest dreamer?"),
("22", "Wer verbringt die meiste Zeit im Büro?", "Who spends the most time in the office?"),
("22", "Wer würde am ehesten eine neue Erfindung machen?", "Who is most likely to make a new invention?"),
("22", "Wer ist der größte Idealist?", "Who is the biggest idealist?"),
("22", "Wer liebt am meisten Abenteuer?", "Who loves adventures the most?"),
("22", "Wer würde am ehesten eine Fremdsprache fließend lernen?", "Who is most likely to become fluent in a foreign language?"),
("22", "Wer ist der größte Optimist?", "Who is the biggest optimist?"),
("22", "Wer trinkt am meisten Alkohol?", "Who drinks the most alcohol?"),
("22", "Wer würde am ehesten einen Gedichtband veröffentlichen?", "Who is most likely to publish a book of poetry?"),
("22", "Wer ist der/die zynischste?", "Who is the most cynical?"),
("22", "Wer verbringt die meiste Zeit beim Shoppen?", "Who spends the most time shopping?"),
("22", "Wer würde am ehesten ein Museum besuchen?", "Who is most likely to visit a museum?"),
("22", "Wer ist der größte Realist?", "Who is the biggest realist?"),
("22", "Wer isst am liebsten Schokolade?", "Who likes chocolate the most?"),
("22", "Wer würde am ehesten einen Bestseller schreiben?", "Who is most likely to write a bestseller?"),
("22", "Wer ist der/die idealistischste?", "Who is the most idealistic?"),
("22", "Wer liebt am meisten Filme?", "Who loves movies the most?"),
("22", "Wer würde am ehesten ein berühmter Schauspieler werden?", "Who is most likely to become a famous actor?"),
("22", "Wer ist der/die rationalste?", "Who is the most rational?"),
("22", "Wer verbringt die meiste Zeit beim Kochen?", "Who spends the most time cooking?"),
("22", "Wer würde am ehesten eine neue Diät ausprobieren?", "Who is most likely to try a new diet?"),
("22", "Wer ist der/die optimistischste?", "Who is the most optimistic?"),
("22", "Wer liebt am meisten Katzen?", "Who loves cats the most?"),
("22", "Wer würde am ehesten ein berühmter Künstler werden?", "Who is most likely to become a famous artist?"),
("22", "Wer ist der größte Romantiker?", "Who is the biggest romantic?"),
("22", "Wer verbringt die meiste Zeit im Fitnessstudio?", "Who spends the most time in the gym?"),
("22", "Wer würde am ehesten ein wissenschaftliches Paper veröffentlichen?", "Who is most likely to publish a scientific paper?"),
("22", "Wer ist der/die kreativste?", "Who is the most creative?"),
("22", "Wer liebt am meisten Hunde?", "Who loves dogs the most?"),
("22", "Wer würde am ehesten eine neue Tanzart lernen?", "Who is most likely to learn a new dance style?"),
("22", "Wer ist der/die pessimistischste?", "Who is the most pessimistic?"),
("22", "Wer verbringt die meiste Zeit im Internet?", "Who spends the most time on the internet?"),
("22", "Wer würde am ehesten eine eigene TV-Show moderieren?", "Who is most likely to host their own TV show?"),
("22", "Wer ist der/die spirituellste?", "Who is the most spiritual?"),
("22", "Wer liebt am meisten Abenteuer?", "Who loves adventures the most?"),
("22", "Wer würde am ehesten eine neue Sportart erlernen?", "Who is most likely to learn a new sport?"),
("22", "Wer ist der/die rationalste?", "Who is the most rational?"),
("22", "Wer verbringt die meiste Zeit mit Arbeiten?", "Who spends the most time working?"),
("22", "Wer würde am ehesten ein neues Musikinstrument lernen?", "Who is most likely to learn a new musical instrument?"),
("22", "Wer ist der/die perfektionistischste?", "Who is the most perfectionistic?"),
("22", "Wer liebt am meisten Schokolade?", "Who loves chocolate the most?"),
("22", "Wer würde am ehesten ein berühmter Koch werden?", "Who is most likely to become a famous chef?"),
("22", "Wer ist der größte Skeptiker?", "Who is the biggest skeptic?"),
("22", "Wer verbringt die meiste Zeit mit Sport?", "Who spends the most time doing sports?"),
("22", "Wer würde am ehesten ein Weltwunder besuchen?", "Who is most likely to visit a world wonder?"),
("22", "Wer ist der/die idealistischste?", "Who is the most idealistic?"),
("22", "Wer liebt am meisten Fotografie?", "Who loves photography the most?"),
("22", "Wer würde am ehesten eine neue Religion gründen?", "Who is most likely to start a new religion?"),
("22", "Wer ist der größte Träumer?", "Who is the biggest dreamer?"),
("22", "Wer verbringt die meiste Zeit mit Entspannen?", "Who spends the most time relaxing?"),
("22", "Wer würde am ehesten eine neue Technologie entwickeln?", "Who is most likely to develop a new technology?"),
("22", "Wer ist der/die abenteuerlustigste?", "Who is the most adventurous?"),
("22", "Wer liebt am meisten Katzen?", "Who loves cats the most?"),
("22", "Wer würde am ehesten eine neue Geschäftsidee entwickeln?", "Who is most likely to develop a new business idea?"),
("22", "Wer ist der größte Skeptiker?", "Who is the biggest skeptic?"),
("22", "Wer verbringt die meiste Zeit mit Lernen?", "Who spends the most time studying?"),
("22", "Wer würde am ehesten ein berühmter Blogger werden?", "Who is most likely to become a famous blogger?"),
("22", "Wer ist der größte Realist?", "Who is the biggest realist?"),
("22", "Wer liebt am meisten Abenteuer?", "Who loves adventures the most?"),
("22", "Wer würde am ehesten ein neues Kunstwerk schaffen?", "Who is most likely to create a new piece of art?"),
("22", "Wer ist der größte Denker?", "Who is the biggest thinker?"),
("22", "Wer verbringt die meiste Zeit am Computer?", "Who spends the most time on the computer?"),
("22", "Wer würde am ehesten eine neue Diät ausprobieren?", "Who is most likely to try a new diet?"),
("22", "Wer ist der größte Optimist?", "Who is the biggest optimist?"),
("22", "Wer liebt am meisten Hunde?", "Who loves dogs the most?"),
("22", "Wer würde am ehesten ein neues Hobby anfangen?", "Who is most likely to start a new hobby?"),
("22", "Wer ist der/die rationalste?", "Who is the most rational?"),
("22", "Wer verbringt die meiste Zeit mit Reisen?", "Who spends the most time traveling?"),
("22", "Wer würde am ehesten ein berühmter Schauspieler werden?", "Who is most likely to become a famous actor?"),
("22", "Wer ist der/die pessimistischste?", "Who is the most pessimistic?"),
("22", "Wer verbringt die meiste Zeit mit Schreiben?", "Who spends the most time writing?"),
("22", "Wer würde am ehesten ein wissenschaftliches Experiment durchführen?", "Who is most likely to conduct a scientific experiment?"),
("22", "Wer ist der größte Realist?", "Who is the biggest realist?"),
("22", "Wer liebt am meisten Musik?", "Who loves music the most?"),
("22", "Wer würde am ehesten ein neues Geschäft eröffnen?", "Who is most likely to open a new business?"),
("22", "Wer ist der größte Optimist?", "Who is the biggest optimist?"),
("22", "Wer verbringt die meiste Zeit mit Arbeiten?", "Who spends the most time working?"),
("22", "Wer würde am ehesten ein berühmter Schriftsteller werden?", "Who is most likely to become a famous writer?"),
("22", "Wer ist der größte Skeptiker?", "Who is the biggest skeptic?"),
("22", "Wer verbringt die meiste Zeit mit Sport?", "Who spends the most time doing sports?"),
("22", "Wer würde am ehesten eine berühmte Entdeckung machen?", "Who is most likely to make a famous discovery?"),
("22", "Wer ist der größte Idealist?", "Who is the biggest idealist?"),
("22", "Wer liebt am meisten Katzen?", "Who loves cats the most?"),
("22", "Wer würde am ehesten ein berühmtes Unternehmen gründen?", "Who is most likely to start a famous company?"),
("22", "Wer ist der größte Denker?", "Who is the biggest thinker?"),
("22", "Wer verbringt die meiste Zeit mit Lesen?", "Who spends the most time reading?"),
("22", "Wer würde am ehesten ein berühmtes Gemälde malen?", "Who is most likely to paint a famous painting?"),
("22", "Wer ist der größte Romantiker?", "Who is the biggest romantic?"),
("22", "Wer verbringt die meiste Zeit im Fitnessstudio?", "Who spends the most time in the gym?"),
("22", "Wer würde am ehesten ein wissenschaftliches Buch schreiben?", "Who is most likely to write a scientific book?"),
("22", "Wer ist der größte Perfektionist?", "Who is the biggest perfectionist?"),
("22", "Wer verbringt die meiste Zeit am Strand?", "Who spends the most time at the beach?"),
("22", "Wer würde am ehesten eine berühmte Erfindung machen?", "Who is most likely to make a famous invention?"),
("22", "Wer ist der größte Träumer?", "Who is the biggest dreamer?"),
("22", "Wer liebt am meisten Abenteuer?", "Who loves adventures the most?"),
("22", "Wer würde am ehesten ein berühmter Künstler werden?", "Who is most likely to become a famous artist?"),
("22", "Wer ist der größte Skeptiker?", "Who is the biggest skeptic?"),
("22", "Wer verbringt die meiste Zeit mit Arbeiten?", "Who spends the most time working?"),
("22", "Wer würde am ehesten ein berühmtes Lied schreiben?", "Who is most likely to write a famous song?"),
("22", "Wer ist der größte Idealist?", "Who is the biggest idealist?"),
("22", "Wer liebt am meisten Hunde?", "Who loves dogs the most?"),
("22", "Wer würde am ehesten ein berühmter Tänzer werden?", "Who is most likely to become a famous dancer?"),
("22", "Wer ist der größte Realist?", "Who is the biggest realist?"),
("22", "Wer verbringt die meiste Zeit mit Lernen?", "Who spends the most time studying?"),
("22", "Wer würde am ehesten eine berühmte Technologie entwickeln?", "Who is most likely to develop a famous technology?"),
("22", "Wer ist der größte Optimist?", "Who is the biggest optimist?"),
("22", "Wer verbringt die meiste Zeit mit Entspannen?", "Who spends the most time relaxing?"),
("22", "Wer würde am ehesten ein berühmtes Buch schreiben?", "Who is most likely to write a famous book?");
