
INSERT INTO game_klassiker_questions (fk_pool, content, content_english) VALUES
("22", "Wer ist die mutigste Person?", "Who is the bravest person?"),
("22", "Wer macht die besten Witze?", "Who tells the best jokes?"),
("22", "Wer würde am ehesten eine Bank ausrauben?", "Who would most likely rob a bank?"),
("22", "Wer ist die größte Tratschtante?", "Who is the biggest gossip?"),
("22", "Wer macht am meisten Sport?", "Who exercises the most?"),
("22", "Wer wird als erstes Kinder haben?", "Who will have children first?"),
("22", "Wer ist die pessimistischste Person?", "Who is the most pessimistic person?"),
("22", "Wer kocht die besten Mahlzeiten?", "Who cooks the best meals?"),
("22", "Wer würde am ehesten auf einer einsamen Insel überleben?", "Who would most likely survive on a deserted island?"),
("22", "Wer ist die organisierteste Person?", "Who is the most organized person?"),
("22", "Wer schaut am meisten Fernsehen?", "Who watches the most TV?"),
("22", "Wer wird am ehesten eine eigene Firma gründen?", "Who is most likely to start their own business?"),
("22", "Wer ist die empathischste Person?", "Who is the most empathetic person?"),
("22", "Wer liest die meisten Bücher?", "Who reads the most books?"),
("22", "Wer würde am ehesten eine Reality-Show gewinnen?", "Who would most likely win a reality show?"),
("22", "Wer ist die unordentlichste Person?", "Who is the messiest person?"),
("22", "Wer singt am häufigsten?", "Who sings the most often?"),
("22", "Wer würde am ehesten eine Weltreise machen?", "Who is most likely to go on a world tour?"),
("22", "Wer ist die geduldigste Person?", "Who is the most patient person?"),
("22", "Wer geht am häufigsten aus?", "Who goes out the most?"),
("22", "Wer würde am ehesten ein Buch schreiben?", "Who is most likely to write a book?"),
("22", "Wer ist die großzügigste Person?", "Who is the most generous person?"),
("22", "Wer backt die besten Kuchen?", "Who bakes the best cakes?"),
("22", "Wer würde am ehesten ein Tattoo stechen lassen?", "Who is most likely to get a tattoo?"),
("22", "Wer ist die kreativste Person?", "Who is the most creative person?"),
("22", "Wer geht am häufigsten shoppen?", "Who goes shopping the most?"),
("22", "Wer würde am ehesten einem Fremden helfen?", "Who is most likely to help a stranger?"),
("22", "Wer ist die lustigste Person?", "Who is the funniest person?"),
("22", "Wer kocht am wenigsten?", "Who cooks the least?"),
("22", "Wer würde am ehesten einen Marathon laufen?", "Who is most likely to run a marathon?"),
("22", "Wer ist die neugierigste Person?", "Who is the most curious person?"),
("22", "Wer fährt das beste Auto?", "Who drives the best car?"),
("22", "Wer würde am ehesten eine App entwickeln?", "Who is most likely to develop an app?"),
("22", "Wer ist die sportlichste Person?", "Who is the most athletic person?"),
("22", "Wer isst am wenigsten Fast Food?", "Who eats the least fast food?"),
("22", "Wer würde am ehesten im Ausland leben?", "Who is most likely to live abroad?"),
("22", "Wer ist die vertrauenswürdigste Person?", "Who is the most trustworthy person?"),
("22", "Wer kauft am meisten online ein?", "Who buys the most online?"),
("22", "Wer würde am ehesten Präsident/in werden?", "Who is most likely to become president?"),
("22", "Wer ist die spontanste Person?", "Who is the most spontaneous person?"),
("22", "Wer hat das beste Lachen?", "Who has the best laugh?"),
("22", "Wer würde am ehesten einen Roadtrip machen?", "Who is most likely to go on a road trip?"),
("22", "Wer ist die ehrlichste Person?", "Who is the most honest person?"),
("22", "Wer telefoniert am längsten?", "Who talks on the phone the longest?"),
("22", "Wer würde am ehesten eine Erfindung patentieren lassen?", "Who is most likely to patent an invention?"),
("22", "Wer ist die pünktlichste Person?", "Who is the most punctual person?"),
("22", "Wer hat die meisten Haustiere?", "Who has the most pets?"),
("22", "Wer würde am ehesten ein Restaurant eröffnen?", "Who is most likely to open a restaurant?"),
("22", "Wer ist die modebewussteste Person?", "Who is the most fashion-conscious person?"),
("22", "Wer gibt am meisten Geld aus?", "Who spends the most money?"),
("22", "Wer würde am ehesten ein Extremsport betreiben?", "Who is most likely to do extreme sports?"),
("22", "Wer ist die optimistischste Person?", "Who is the most optimistic person?"),
("22", "Wer hat das ordentlichste Zuhause?", "Who has the neatest home?"),
("22", "Wer würde am ehesten eine politische Kampagne starten?", "Who is most likely to start a political campaign?"),
("22", "Wer ist die musikalischste Person?", "Who is the most musical person?"),
("22", "Wer sieht die meisten Filme?", "Who watches the most movies?"),
("22", "Wer würde am ehesten eine gemeinnützige Organisation gründen?", "Who is most likely to start a non-profit organization?"),
("22", "Wer ist die abenteuerlustigste Person?", "Who is the most adventurous person?"),
("22", "Wer verbringt am meisten Zeit in sozialen Medien?", "Who spends the most time on social media?"),
("22", "Wer würde am ehesten einen YouTube-Kanal starten?", "Who is most likely to start a YouTube channel?"),
("22", "Wer ist die vorsichtigste Person?", "Who is the most cautious person?"),
("22", "Wer bleibt am längsten wach?", "Who stays up the longest?"),
("22", "Wer würde am ehesten ein Kunstwerk schaffen?", "Who is most likely to create a piece of art?"),
("22", "Wer ist die hilfsbereiteste Person?", "Who is the most helpful person?"),
("22", "Wer reist am häufigsten?", "Who travels the most?"),
("22", "Wer würde am ehesten eine Spende an eine Wohltätigkeitsorganisation machen?", "Who is most likely to make a donation to a charity?"),
("22", "Wer ist die witzigste Person?", "Who is the funniest person?"),
("22", "Wer hat die meisten Hobbys?", "Who has the most hobbies?"),
("22", "Wer würde am ehesten ein wissenschaftliches Experiment durchführen?", "Who is most likely to conduct a scientific experiment?"),
("22", "Wer ist die freundliche Person?", "Who is the friendliest person?"),
("22", "Wer verbringt am meisten Zeit im Fitnessstudio?", "Who spends the most time at the gym?"),
("22", "Wer würde am ehesten ein Abenteuer im Dschungel erleben?", "Who is most likely to have an adventure in the jungle?"),
("22", "Wer ist die geselligste Person?", "Who is the most sociable person?"),
("22", "Wer isst am gesündesten?", "Who eats the healthiest?"),
("22", "Wer würde am ehesten ein eigenes Modelabel gründen?", "Who is most likely to start their own fashion label?"),
("22", "Wer ist die zuverlässigste Person?", "Who is the most reliable person?"),
("22", "Wer trinkt am meisten Kaffee?", "Who drinks the most coffee?"),
("22", "Wer würde am ehesten in einem Horrorfilm überleben?", "Who is most likely to survive in a horror movie?"),
("22", "Wer ist die inspirierendste Person?", "Who is the most inspiring person?"),
("22", "Wer spielt am meisten Videospiele?", "Who plays the most video games?"),
("22", "Wer würde am ehesten einen Schatz finden?", "Who is most likely to find a treasure?"),
("22", "Wer ist die zielstrebigste Person?", "Who is the most ambitious person?"),
("22", "Wer verbringt am meisten Zeit am Strand?", "Who spends the most time at the beach?"),
("22", "Wer würde am ehesten in einer Reality-Show mitmachen?", "Who is most likely to participate in a reality show?"),
("22", "Wer ist die intelligenteste Person?", "Who is the most intelligent person?"),
("22", "Wer geht am häufigsten ins Kino?", "Who goes to the cinema the most?"),
("22", "Wer würde am ehesten ein Unternehmen leiten?", "Who is most likely to run a company?"),
("22", "Wer ist die schüchternste Person?", "Who is the shyest person?"),
("22", "Wer hat die meisten Freunde?", "Who has the most friends?"),
("22", "Wer würde am ehesten einen Podcast starten?", "Who is most likely to start a podcast?"),
("22", "Wer ist die optimistischste Person?", "Who is the most optimistic person?"),
("22", "Wer verbringt am meisten Zeit am Computer?", "Who spends the most time on the computer?"),
("22", "Wer würde am ehesten ein Musikinstrument lernen?", "Who is most likely to learn a musical instrument?"),
("22", "Wer ist die ruhigste Person?", "Who is the calmest person?"),
("22", "Wer verbringt am meisten Zeit mit seinen/ihren Haustieren?", "Who spends the most time with their pets?"),
("22", "Wer würde am ehesten eine berühmte Persönlichkeit kennenlernen?", "Who is most likely to meet a celebrity?"),
("22", "Wer ist die großzügigste Person?", "Who is the most generous person?"),
("22", "Wer geht am häufigsten campen?", "Who goes camping the most?"),
("22", "Wer würde am ehesten einen Bestseller schreiben?", "Who is most likely to write a bestseller?"),
("22", "Wer ist die nachdenklichste Person?", "Who is the most thoughtful person?"),
("22", "Wer verbringt am meisten Zeit im Garten?", "Who spends the most time in the garden?"),
("22", "Wer würde am ehesten eine TV-Show moderieren?", "Who is most likely to host a TV show?"),
("22", "Wer ist die unabhängigste Person?", "Who is the most independent person?"),
("22", "Wer spielt die meisten Brettspiele?", "Who plays the most board games?"),
("22", "Wer würde am ehesten eine eigene Insel kaufen?", "Who is most likely to buy their own island?"),
("22", "Wer ist die selbstbewussteste Person?", "Who is the most confident person?"),
("22", "Wer verbringt am meisten Zeit im Park?", "Who spends the most time in the park?"),
("22", "Wer würde am ehesten einen preisgekrönten Film drehen?", "Who is most likely to make an award-winning film?"),
("22", "Wer ist die leidenschaftlichste Person?", "Who is the most passionate person?"),
("22", "Wer isst am meisten Schokolade?", "Who eats the most chocolate?"),
("22", "Wer würde am ehesten in einem Musical auftreten?", "Who is most likely to perform in a musical?"),
("22", "Wer ist die humorvollste Person?", "Who has the best sense of humor?"),
("22", "Wer gibt am wenigsten Geld aus?", "Who spends the least money?"),
("22", "Wer würde am ehesten ein Museum besuchen?", "Who is most likely to visit a museum?"),
("22", "Wer ist die vorsichtigste Person?", "Who is the most careful person?"),
("22", "Wer hat die meisten Pflanzen?", "Who has the most plants?"),
("22", "Wer würde am ehesten eine neue Sprache lernen?", "Who is most likely to learn a new language?"),
("22", "Wer ist die gesprächigste Person?", "Who is the most talkative person?"),
("22", "Wer isst am meisten Gemüse?", "Who eats the most vegetables?"),
("22", "Wer würde am ehesten eine Rallye fahren?", "Who is most likely to drive in a rally?"),
("22", "Wer ist die sparsamste Person?", "Who is the most frugal person?"),
("22", "Wer hat die meisten Reisen unternommen?", "Who has traveled the most?"),
("22", "Wer würde am ehesten ein Märchenbuch schreiben?", "Who is most likely to write a fairy tale book?"),
("22", "Wer ist die aktivste Person?", "Who is the most active person?"),
("22", "Wer verbringt am meisten Zeit mit Familie?", "Who spends the most time with family?"),
("22", "Wer würde am ehesten ein Hotel eröffnen?", "Who is most likely to open a hotel?"),
("22", "Wer ist die friedlichste Person?", "Who is the most peaceful person?"),
("22", "Wer liebt am meisten Tiere?", "Who loves animals the most?"),
("22", "Wer würde am ehesten ein Geheimnis bewahren?", "Who is most likely to keep a secret?"),
("22", "Wer ist die selbstloseste Person?", "Who is the most selfless person?"),
("22", "Wer hat den besten Modegeschmack?", "Who has the best fashion sense?"),
("22", "Wer würde am ehesten ein eigenes Café eröffnen?", "Who is most likely to open their own café?"),
("22", "Wer ist die willensstärkste Person?", "Who is the most determined person?"),
("22", "Wer geht am häufigsten ins Theater?", "Who goes to the theater the most?"),
("22", "Wer würde am ehesten ein Haus auf dem Land kaufen?", "Who is most likely to buy a house in the countryside?"),
("22", "Wer ist die kontaktfreudigste Person?", "Who is the most outgoing person?"),
("22", "Wer isst am meisten Obst?", "Who eats the most fruit?"),
("22", "Wer würde am ehesten eine Erfindung machen?", "Who is most likely to make an invention?"),
("22", "Wer ist die abenteuerlichste Person?", "Who is the most adventurous person?"),
("22", "Wer verbringt am meisten Zeit mit Lesen?", "Who spends the most time reading?"),
("22", "Wer würde am ehesten ein Theaterstück schreiben?", "Who is most likely to write a play?"),
("22", "Wer ist die besonnenste Person?", "Who is the most prudent person?"),
("22", "Wer hat die meisten Haustiere?", "Who has the most pets?"),
("22", "Wer würde am ehesten einen Berg besteigen?", "Who is most likely to climb a mountain?"),
("22", "Wer ist die fürsorglichste Person?", "Who is the most caring person?"),
("22", "Wer verbringt am meisten Zeit mit Freunden?", "Who spends the most time with friends?"),
("22", "Wer würde am ehesten eine TV-Show gewinnen?", "Who is most likely to win a TV show?"),
("22", "Wer ist die abenteuerlustigste Person?", "Who is the most adventurous person?"),
("22", "Wer isst am meisten Fleisch?", "Who eats the most meat?"),
("22", "Wer würde am ehesten ein Weltrekord brechen?", "Who is most likely to break a world record?"),
("22", "Wer ist die nachdenklichste Person?", "Who is the most thoughtful person?"),
("22", "Wer liebt am meisten die Natur?", "Who loves nature the most?"),
("22", "Wer würde am ehesten in den Weltraum reisen?", "Who is most likely to travel to space?"),
("22", "Wer ist die optimistischste Person?", "Who is the most optimistic person?"),
("22", "Wer verbringt am meisten Zeit im Fitnessstudio?", "Who spends the most time at the gym?"),
("22", "Wer würde am ehesten ein neues Unternehmen gründen?", "Who is most likely to start a new business?"),
("22", "Wer ist die mitfühlendste Person?", "Who is the most compassionate person?"),
("22", "Wer verbringt am meisten Zeit im Freien?", "Who spends the most time outdoors?"),
("22", "Wer würde am ehesten ein Lied schreiben?", "Who is most likely to write a song?"),
("22", "Wer ist die weiseste Person?", "Who is the wisest person?"),
("22", "Wer verbringt am meisten Zeit in der Küche?", "Who spends the most time in the kitchen?"),
("22", "Wer würde am ehesten ein Auto reparieren?", "Who is most likely to repair a car?"),
("22", "Wer ist die nachdenklichste Person?", "Who is the most considerate person?"),
("22", "Wer verbringt am meisten Zeit mit Kunst?", "Who spends the most time with art?"),
("22", "Wer würde am ehesten einen Marathon laufen?", "Who is most likely to run a marathon?"),
("22", "Wer ist die klügste Person?", "Who is the wisest person?"),
("22", "Wer verbringt am meisten Zeit auf Partys?", "Who spends the most time at parties?"),
("22", "Wer würde am ehesten ein Museum eröffnen?", "Who is most likely to open a museum?"),
("22", "Wer ist die reflektierteste Person?", "Who is the most reflective person?"),
("22", "Wer verbringt am meisten Zeit in der Natur?", "Who spends the most time in nature?"),
("22", "Wer würde am ehesten ein Geheimnis bewahren?", "Who is most likely to keep a secret?"),
("22", "Wer ist die hilfsbereiteste Person?", "Who is the most helpful person?"),
("22", "Wer verbringt am meisten Zeit mit Technologie?", "Who spends the most time with technology?"),
("22", "Wer würde am ehesten ein Haus bauen?", "Who is most likely to build a house?"),
("22", "Wer ist die treuste Person?", "Who is the most loyal person?"),
("22", "Wer verbringt am meisten Zeit mit Fotografie?", "Who spends the most time with photography?"),
("22", "Wer würde am ehesten einen Dokumentarfilm drehen?", "Who is most likely to make a documentary?"),
("22", "Wer ist die kreativste Person?", "Who is the most creative person?"),
("22", "Wer verbringt am meisten Zeit mit Kochen?", "Who spends the most time cooking?"),
("22", "Wer würde am ehesten eine Fernsehsendung moderieren?", "Who is most likely to host a TV show?"),
("22", "Wer ist die visionärste Person?", "Who is the most visionary person?"),
("22", "Wer verbringt am meisten Zeit mit Sport?", "Who spends the most time on sports?"),
("22", "Wer würde am ehesten ein Konzert organisieren?", "Who is most likely to organize a concert?"),
("22", "Wer ist die fürsorglichste Person?", "Who is the most caring person?"),
("22", "Wer verbringt am meisten Zeit auf Reisen?", "Who spends the most time traveling?"),
("22", "Wer würde am ehesten eine wissenschaftliche Entdeckung machen?", "Who is most likely to make a scientific discovery?"),
("22", "Wer ist die geduldigste Person?", "Who is the most patient person?"),
("22", "Wer verbringt am meisten Zeit im Wasser?", "Who spends the most time in the water?"),
("22", "Wer würde am ehesten ein neues Instrument lernen?", "Who is most likely to learn a new instrument?"),
("22", "Wer ist die herzlichste Person?", "Who is the warmest person?"),
("22", "Wer verbringt am meisten Zeit mit Tieren?", "Who spends the most time with animals?"),
("22", "Wer würde am ehesten ein eigenes Unternehmen gründen?", "Who is most likely to start their own business?"),
("22", "Wer ist die ruhigste Person?", "Who is the calmest person?"),
("22", "Wer verbringt am meisten Zeit mit Meditation?", "Who spends the most time meditating?"),
("22", "Wer würde am ehesten ein YouTube-Star werden?", "Who is most likely to become a YouTube star?"),
("22", "Wer ist die inspirierendste Person?", "Who is the most inspiring person?"),
("22", "Wer verbringt am meisten Zeit in der Sonne?", "Who spends the most time in the sun?"),
("22", "Wer würde am ehesten ein neues Buch schreiben?", "Who is most likely to write a new book?"),
("22", "Wer ist die selbstbewussteste Person?", "Who is the most confident person?"),
("22", "Wer verbringt am meisten Zeit mit Basteln?", "Who spends the most time crafting?"),
("22", "Wer würde am ehesten einen Weltrekord aufstellen?", "Who is most likely to set a world record?"),
("22", "Wer ist die optimistischste Person?", "Who is the most optimistic person?"),
("22", "Wer verbringt am meisten Zeit mit Lesen?", "Who spends the most time reading?"),
("22", "Wer würde am ehesten ein Festival organisieren?", "Who is most likely to organize a festival?"),
("22", "Wer ist die abenteuerlustigste Person?", "Who is the most adventurous person?"),
("22", "Wer verbringt am meisten Zeit mit Musik?", "Who spends the most time with music?"),
("22", "Wer würde am ehesten ein Theaterstück schreiben?", "Who is most likely to write a play?"),
("22", "Wer ist die selbstloseste Person?", "Who is the most selfless person?"),
("22", "Wer verbringt am meisten Zeit mit Freiwilligenarbeit?", "Who spends the most time volunteering?"),
("22", "Wer würde am ehesten eine Fernsehsendung leiten?", "Who is most likely to direct a TV show?"),
("22", "Wer ist die aufgeschlossenste Person?", "Who is the most open-minded person?"),
("22", "Wer verbringt am meisten Zeit mit Tanzen?", "Who spends the most time dancing?"),
("22", "Wer würde am ehesten eine Erfindung patentieren?", "Who is most likely to patent an invention?"),
("22", "Wer ist die witzigste Person?", "Who is the funniest person?"),
("22", "Wer verbringt am meisten Zeit mit Schreiben?", "Who spends the most time writing?"),
("22", "Wer würde am ehesten ein Abenteuer im Dschungel überleben?", "Who is most likely to survive an adventure in the jungle?"),
("22", "Wer ist die verständnisvollste Person?", "Who is the most understanding person?"),
("22", "Wer verbringt am meisten Zeit in der Bibliothek?", "Who spends the most time in the library?"),
("22", "Wer würde am ehesten einen Preis für Frieden gewinnen?", "Who is most likely to win a peace prize?"),
("22", "Wer ist die motivierteste Person?", "Who is the most motivated person?"),
("22", "Wer verbringt am meisten Zeit im Internet?", "Who spends the most time on the internet?"),
("22", "Wer würde am ehesten einen Zirkus leiten?", "Who is most likely to run a circus?"),
("22", "Wer ist die intuitivste Person?", "Who is the most intuitive person?"),
("22", "Wer verbringt am meisten Zeit mit Malen?", "Who spends the most time painting?"),
("22", "Wer würde am ehesten ein Puzzle lösen?", "Who is most likely to solve a puzzle?"),
("22", "Wer ist die hilfsbereiteste Person?", "Who is the most helpful person?"),
("22", "Wer verbringt am meisten Zeit mit Mode?", "Who spends the most time on fashion?"),
("22", "Wer würde am ehesten einen Urlaub planen?", "Who is most likely to plan a vacation?"),
("22", "Wer ist die kommunikativste Person?", "Who is the most communicative person?"),
("22", "Wer verbringt am meisten Zeit mit Fotografie?", "Who spends the most time on photography?"),
("22", "Wer würde am ehesten ein Geheimnis für immer bewahren?", "Who is most likely to keep a secret forever?"),
("22", "Wer ist die fantasievollste Person?", "Who is the most imaginative person?"),
("22", "Wer verbringt am meisten Zeit am Telefon?", "Who spends the most time on the phone?"),
("22", "Wer würde am ehesten einen wissenschaftlichen Artikel veröffentlichen?", "Who is most likely to publish a scientific article?"),
("22", "Wer ist die verantwortungsvollste Person?", "Who is the most responsible person?"),
("22", "Wer verbringt am meisten Zeit in der Küche?", "Who spends the most time in the kitchen?"),
("22", "Wer würde am ehesten ein Gedicht schreiben?", "Who is most likely to write a poem?"),
("22", "Wer ist die nachdenklichste Person?", "Who is the most thoughtful person?"),
("22", "Wer verbringt am meisten Zeit mit Lernen?", "Who spends the most time studying?"),
("22", "Wer würde am ehesten ein Denkmal errichten?", "Who is most likely to erect a monument?"),
("22", "Wer ist die optimistischste Person?", "Who is the most optimistic person?"),
("22", "Wer verbringt am meisten Zeit im Büro?", "Who spends the most time in the office?"),
("22", "Wer würde am ehesten ein Geheimnis bewahren?", "Who is most likely to keep a secret?"),
("22", "Wer ist die verantwortungsvollste Person?", "Who is the most responsible person?"),
("22", "Wer verbringt am meisten Zeit mit Fitness?", "Who spends the most time on fitness?"),
("22", "Wer würde am ehesten ein Meisterwerk schaffen?", "Who is most likely to create a masterpiece?"),
("22", "Wer ist die selbstloseste Person?", "Who is the most selfless person?"),
("22", "Wer verbringt am meisten Zeit mit Meditation?", "Who spends the most time meditating?"),
("22", "Wer würde am ehesten eine Entdeckung machen?", "Who is most likely to make a discovery?"),
("22", "Wer ist die geduldigste Person?", "Who is the most patient person?"),
("22", "Wer verbringt am meisten Zeit am Meer?", "Who spends the most time by the sea?"),
("22", "Wer würde am ehesten ein Spiel entwickeln?", "Who is most likely to develop a game?"),
("22", "Wer ist die weiseste Person?", "Who is the wisest person?"),
("22", "Wer verbringt am meisten Zeit im Garten?", "Who spends the most time in the garden?"),
("22", "Wer würde am ehesten eine wissenschaftliche Arbeit schreiben?", "Who is most likely to write a scientific paper?"),
("22", "Wer ist die abenteuerlustigste Person?", "Who is the most adventurous person?"),
("22", "Wer verbringt am meisten Zeit mit Tieren?", "Who spends the most time with animals?"),
("22", "Wer würde am ehesten eine App entwickeln?", "Who is most likely to develop an app?"),
("22", "Wer ist die optimistischste Person?", "Who is the most optimistic person?"),
("22", "Wer verbringt am meisten Zeit mit Pflanzen?", "Who spends the most time with plants?"),
("22", "Wer würde am ehesten ein Geheimnis für immer bewahren?", "Who is most likely to keep a secret forever?"),
("22", "Wer ist die kommunikativste Person?", "Who is the most communicative person?"),
("22", "Wer verbringt am meisten Zeit in sozialen Medien?", "Who spends the most time on social media?"),
("22", "Wer würde am ehesten ein Lied schreiben?", "Who is most likely to write a song?"),
("22", "Wer ist die hilfsbereiteste Person?", "Who is the most helpful person?"),
("22", "Wer verbringt am meisten Zeit mit Freunden?", "Who spends the most time with friends?"),
("22", "Wer würde am ehesten eine neue Sprache lernen?", "Who is most likely to learn a new language?"),
("22", "Wer ist die fantasievollste Person?", "Who is the most imaginative person?"),
("22", "Wer verbringt am meisten Zeit mit Spielen?", "Who spends the most time playing games?"),
("22", "Wer würde am ehesten ein Unternehmen leiten?", "Who is most likely to run a company?"),
("22", "Wer ist die abenteuerlustigste Person?", "Who is the most adventurous person?"),
("22", "Wer verbringt am meisten Zeit am Strand?", "Who spends the most time at the beach?"),
("22", "Wer würde am ehesten ein Geheimnis bewahren?", "Who is most likely to keep a secret?"),
("22", "Wer ist die kommunikativste Person?", "Who is the most communicative person?"),
("22", "Wer verbringt am meisten Zeit mit Fitness?", "Who spends the most time on fitness?"),
("22", "Wer würde am ehesten ein neues Instrument lernen?", "Who is most likely to learn a new instrument?"),
("22", "Wer ist die hilfsbereiteste Person?", "Who is the most helpful person?"),
("22", "Wer verbringt am meisten Zeit mit Reisen?", "Who spends the most time traveling?"),
("22", "Wer würde am ehesten eine Fernsehsendung leiten?", "Who is most likely to direct a TV show?"),
("22", "Wer ist die selbstloseste Person?", "Who is the most selfless person?"),
("22", "Wer verbringt am meisten Zeit mit Kunst?", "Who spends the most time with art?"),
("22", "Wer würde am ehesten ein eigenes Unternehmen gründen?", "Who is most likely to start their own business?"),
("22", "Wer ist die geduldigste Person?", "Who is the most patient person?"),
("22", "Wer verbringt am meisten Zeit im Büro?", "Who spends the most time in the office?"),
("22", "Wer würde am ehesten ein Kunstwerk schaffen?", "Who is most likely to create a piece of art?"),
("22", "Wer ist die kreativste Person?", "Who is the most creative person?"),
("22", "Wer verbringt am meisten Zeit mit Pflanzen?", "Who spends the most time with plants?"),
("22", "Wer würde am ehesten ein neues Buch schreiben?", "Who is most likely to write a new book?"),
("22", "Wer ist die inspirierendste Person?", "Who is the most inspiring person?"),
("22", "Wer verbringt am meisten Zeit mit Lesen?", "Who spends the most time reading?"),
("22", "Wer würde am ehesten einen Podcast starten?", "Who is most likely to start a podcast?"),
("22", "Wer ist die humorvollste Person?", "Who has the best sense of humor?"),
("22", "Wer verbringt am meisten Zeit mit Tanzen?", "Who spends the most time dancing?"),
("22", "Wer würde am ehesten ein Theaterstück schreiben?", "Who is most likely to write a play?"),
("22", "Wer ist die fürsorglichste Person?", "Who is the most caring person?"),
("22", "Wer verbringt am meisten Zeit mit Freiwilligenarbeit?", "Who spends the most time volunteering?"),
("22", "Wer würde am ehesten eine Fernsehsendung moderieren?", "Who is most likely to host a TV show?"),
("22", "Wer ist die kreativste Person?", "Who is the most creative person?"),
("22", "Wer verbringt am meisten Zeit im Garten?", "Who spends the most time in the garden?"),
("22", "Wer würde am ehesten ein Konzert organisieren?", "Who is most likely to organize a concert?"),
("22", "Wer ist die nachdenklichste Person?", "Who is the most thoughtful person?"),
("22", "Wer verbringt am meisten Zeit mit Malen?", "Who spends the most time painting?"),
("22", "Wer würde am ehesten ein Wissenschaftsprojekt starten?", "Who is most likely to start a science project?"),
("22", "Wer ist die selbstbewussteste Person?", "Who is the most confident person?"),
("22", "Wer verbringt am meisten Zeit mit Basteln?", "Who spends the most time crafting?"),
("22", "Wer würde am ehesten ein Rätsel lösen?", "Who is most likely to solve a puzzle?"),
("22", "Wer ist die motivierteste Person?", "Who is the most motivated person?"),
("22", "Wer verbringt am meisten Zeit mit Haustieren?", "Who spends the most time with pets?"),
("22", "Wer würde am ehesten ein neues Sportteam gründen?", "Who is most likely to start a new sports team?"),
("22", "Wer ist die abenteuerlustigste Person?", "Who is the most adventurous person?"),
("22", "Wer verbringt am meisten Zeit mit Spielen?", "Who spends the most time playing games?"),
("22", "Wer würde am ehesten einen neuen Tanz erfinden?", "Who is most likely to invent a new dance?"),
("22", "Wer ist die kontaktfreudigste Person?", "Who is the most outgoing person?"),
("22", "Wer verbringt am meisten Zeit im Park?", "Who spends the most time in the park?"),
("22", "Wer würde am ehesten eine Rallye fahren?", "Who is most likely to drive in a rally?"),
("22", "Wer ist die optimistischste Person?", "Who is the most optimistic person?"),
("22", "Wer verbringt am meisten Zeit mit Familie?", "Who spends the most time with family?"),
("22", "Wer würde am ehesten eine Weltreise machen?", "Who is most likely to go on a world tour?"),
("22", "Wer ist die hilfsbereiteste Person?", "Who is the most helpful person?"),
("22", "Wer verbringt am meisten Zeit mit Lesen?", "Who spends the most time reading?"),
("22", "Wer würde am ehesten ein Museum eröffnen?", "Who is most likely to open a museum?"),
("22", "Wer ist die abenteuerlustigste Person?", "Who is the most adventurous person?"),
("22", "Wer verbringt am meisten Zeit mit Sport?", "Who spends the most time on sports?"),
("22", "Wer würde am ehesten ein Abenteuer im Dschungel überleben?", "Who is most likely to survive an adventure in the jungle?"),
("22", "Wer ist die kommunikativste Person?", "Who is the most communicative person?"),
("22", "Wer verbringt am meisten Zeit mit Kunst?", "Who spends the most time with art?"),
("22", "Wer würde am ehesten ein neues Produkt entwickeln?", "Who is most likely to develop a new product?"),
("22", "Wer ist die fantasievollste Person?", "Who is the most imaginative person?"),
("22", "Wer verbringt am meisten Zeit in der Natur?", "Who spends the most time in nature?"),
("22", "Wer würde am ehesten ein neues Hobby beginnen?", "Who is most likely to start a new hobby?"),
("22", "Wer ist die nachdenklichste Person?", "Who is the most thoughtful person?"),
("22", "Wer verbringt am meisten Zeit am Computer?", "Who spends the most time on the computer?"),
("22", "Wer würde am ehesten ein Geheimnis bewahren?", "Who is most likely to keep a secret?"),
("22", "Wer ist die verantwortungsvollste Person?", "Who is the most responsible person?"),
("22", "Wer verbringt am meisten Zeit mit Videospielen?", "Who spends the most time playing video games?"),
("22", "Wer würde am ehesten eine App entwickeln?", "Who is most likely to develop an app?"),
("22", "Wer ist die fantasievollste Person?", "Who is the most imaginative person?"),
("22", "Wer verbringt am meisten Zeit mit Haustieren?", "Who spends the most time with pets?"),
("22", "Wer würde am ehesten ein Restaurant eröffnen?", "Who is most likely to open a restaurant?"),
("22", "Wer ist die abenteuerlustigste Person?", "Who is the most adventurous person?"),
("22", "Wer verbringt am meisten Zeit mit Fotografie?", "Who spends the most time on photography?"),
("22", "Wer würde am ehesten einen Preis für Wissenschaft gewinnen?", "Who is most likely to win a science award?"),
("22", "Wer ist die hilfsbereiteste Person?", "Who is the most helpful person?"),
("22", "Wer verbringt am meisten Zeit mit Mode?", "Who spends the most time on fashion?"),
("22", "Wer würde am ehesten ein neues Unternehmen gründen?", "Who is most likely to start a new business?"),
("22", "Wer ist die motivierteste Person?", "Who is the most motivated person?"),
("22", "Wer verbringt am meisten Zeit mit Musik?", "Who spends the most time with music?"),
("22", "Wer würde am ehesten ein Theaterstück schreiben?", "Who is most likely to write a play?"),
("22", "Wer ist die kreativste Person?", "Who is the most creative person?"),
("22", "Wer verbringt am meisten Zeit in der Küche?", "Who spends the most time in the kitchen?"),
("22", "Wer würde am ehesten ein neues Sportteam gründen?", "Who is most likely to start a new sports team?"),
("22", "Wer ist die optimistischste Person?", "Who is the most optimistic person?"),
("22", "Wer verbringt am meisten Zeit im Garten?", "Who spends the most time in the garden?"),
("22", "Wer würde am ehesten eine Fernsehsendung leiten?", "Who is most likely to direct a TV show?"),
("22", "Wer ist die weiseste Person?", "Who is the wisest person?"),
("22", "Wer verbringt am meisten Zeit im Büro?", "Who spends the most time in the office?"),
("22", "Wer würde am ehesten ein Buch schreiben?", "Who is most likely to write a book?"),
("22", "Wer ist die reflektierteste Person?", "Who is the most reflective person?"),
("22", "Wer verbringt am meisten Zeit im Park?", "Who spends the most time in the park?"),
("22", "Wer würde am ehesten ein preisgekröntes Foto schießen?", "Who is most likely to take an award-winning photo?"),
("22", "Wer ist die intuitivste Person?", "Who is the most intuitive person?"),
("22", "Wer verbringt am meisten Zeit mit Tieren?", "Who spends the most time with animals?"),
("22", "Wer würde am ehesten eine neue Sprache lernen?", "Who is most likely to learn a new language?"),
("22", "Wer ist die selbstloseste Person?", "Who is the most selfless person?"),
("22", "Wer verbringt am meisten Zeit mit Freunden?", "Who spends the most time with friends?"),
("22", "Wer würde am ehesten ein neues Hobby beginnen?", "Who is most likely to start a new hobby?"),
("22", "Wer ist die hilfsbereiteste Person?", "Who is the most helpful person?"),
("22", "Wer verbringt am meisten Zeit mit Malen?", "Who spends the most time painting?"),
("22", "Wer würde am ehesten ein neues Rezept erfinden?", "Who is most likely to invent a new recipe?"),
("22", "Wer ist die verantwortungsvollste Person?", "Who is the most responsible person?"),
("22", "Wer verbringt am meisten Zeit am Meer?", "Who spends the most time by the sea?"),
("22", "Wer würde am ehesten einen Preis für Kunst gewinnen?", "Who is most likely to win an art award?"),
("22", "Wer ist die geduldigste Person?", "Who is the most patient person?"),
("22", "Wer verbringt am meisten Zeit im Fitnessstudio?", "Who spends the most time at the gym?"),
("22", "Wer würde am ehesten ein Abenteuer im Dschungel erleben?", "Who is most likely to have an adventure in the jungle?"),
("22", "Wer ist die optimistischste Person?", "Who is the most optimistic person?"),
("22", "Wer verbringt am meisten Zeit am Computer?", "Who spends the most time on the computer?"),
("22", "Wer würde am ehesten ein neues Spiel erfinden?", "Who is most likely to invent a new game?"),
("22", "Wer ist die kommunikativste Person?", "Who is the most communicative person?"),
("22", "Wer verbringt am meisten Zeit mit Familie?", "Who spends the most time with family?"),
("22", "Wer würde am ehesten ein Geheimnis bewahren?", "Who is most likely to keep a secret?"),
("22", "Wer ist die hilfsbereiteste Person?", "Who is the most helpful person?"),
("22", "Wer verbringt am meisten Zeit mit Schreiben?", "Who spends the most time writing?"),
("22", "Wer würde am ehesten ein Abenteuer im Weltraum erleben?", "Who is most likely to have an adventure in space?"),
("22", "Wer ist die motivierteste Person?", "Who is the most motivated person?"),
("22", "Wer verbringt am meisten Zeit in der Natur?", "Who spends the most time in nature?"),
("22", "Wer würde am ehesten ein neues Instrument lernen?", "Who is most likely to learn a new instrument?"),
("22", "Wer ist die kreativste Person?", "Who is the most creative person?"),
("22", "Wer verbringt am meisten Zeit im Garten?", "Who spends the most time in the garden?"),
("22", "Wer würde am ehesten eine neue Sprache lernen?", "Who is most likely to learn a new language?"),
("22", "Wer ist die fantasievollste Person?", "Who is the most imaginative person?"),
("22", "Wer verbringt am meisten Zeit mit Fotografie?", "Who spends the most time on photography?"),
("22", "Wer würde am ehesten ein Buch schreiben?", "Who is most likely to write a book?"),
("22", "Wer ist die verantwortungsvollste Person?", "Who is the most responsible person?"),
("22", "Wer verbringt am meisten Zeit mit Videospielen?", "Who spends the most time playing video games?"),
("22", "Wer würde am ehesten ein neues Unternehmen gründen?", "Who is most likely to start a new business?"),
("22", "Wer ist die intuitivste Person?", "Who is the most intuitive person?"),
("22", "Wer verbringt am meisten Zeit mit Pflanzen?", "Who spends the most time with plants?"),
("22", "Wer würde am ehesten ein Restaurant eröffnen?", "Who is most likely to open a restaurant?"),
("22", "Wer ist die optimistischste Person?", "Who is the most optimistic person?"),
("22", "Wer verbringt am meisten Zeit mit Kunst?", "Who spends the most time with art?"),
("22", "Wer würde am ehesten ein Konzert organisieren?", "Who is most likely to organize a concert?"),
("22", "Wer ist die geduldigste Person?", "Who is the most patient person?"),
("22", "Wer verbringt am meisten Zeit mit Sport?", "Who spends the most time on sports?"),
("22", "Wer würde am ehesten ein Abenteuer im Dschungel erleben?", "Who is most likely to have an adventure in the jungle?"),
("22", "Wer ist die abenteuerlustigste Person?", "Who is the most adventurous person?"),
("22", "Wer verbringt am meisten Zeit mit Familie?", "Who spends the most time with family?"),
("22", "Wer würde am ehesten ein neues Buch schreiben?", "Who is most likely to write a new book?"),
("22", "Wer ist die fantasievollste Person?", "Who is the most imaginative person?"),
("22", "Wer verbringt am meisten Zeit mit Freiwilligenarbeit?", "Who spends the most time volunteering?"),
("22", "Wer würde am ehesten eine Fernsehsendung moderieren?", "Who is most likely to host a TV show?"),
("22", "Wer ist die kreative Person?", "Who is the most creative person?"),
("22", "Wer verbringt am meisten Zeit im Park?", "Who spends the most time in the park?"),
("22", "Wer würde am ehesten eine Erfindung machen?", "Who is most likely to make an invention?"),
("22", "Wer ist die hilfsbereiteste Person?", "Who is the most helpful person?"),
("22", "Wer verbringt am meisten Zeit mit Haustieren?", "Who spends the most time with pets?"),
("22", "Wer würde am ehesten ein neues Unternehmen gründen?", "Who is most likely to start a new business?"),
("22", "Wer ist die optimistischste Person?", "Who is the most optimistic person?"),
("22", "Wer verbringt am meisten Zeit mit Tanzen?", "Who spends the most time dancing?"),
("22", "Wer würde am ehesten ein neues Instrument lernen?", "Who is most likely to learn a new instrument?"),
("22", "Wer ist die abenteuerlustigste Person?", "Who is the most adventurous person?"),
("22", "Wer verbringt am meisten Zeit mit Pflanzen?", "Who spends the most time with plants?"),
("22", "Wer würde am ehesten ein eigenes Café eröffnen?", "Who is most likely to open their own café?"),
("22", "Wer ist die verantwortungsvollste Person?", "Who is the most responsible person?"),
("22", "Wer verbringt am meisten Zeit mit Freunden?", "Who spends the most time with friends?"),
("22", "Wer würde am ehesten ein neues Hobby beginnen?", "Who is most likely to start a new hobby?"),
("22", "Wer ist die fantasievollste Person?", "Who is the most imaginative person?"),
("22", "Wer verbringt am meisten Zeit am Computer?", "Who spends the most time on the computer?"),
("22", "Wer würde am ehesten ein Kunstwerk schaffen?", "Who is most likely to create a piece of art?"),
("22", "Wer ist die geduldigste Person?", "Who is the most patient person?"),
("22", "Wer verbringt am meisten Zeit mit Fotografie?", "Who spends the most time on photography?"),
("22", "Wer würde am ehesten ein Abenteuer im Dschungel erleben?", "Who is most likely to have an adventure in the jungle?"),
("22", "Wer ist die optimistischste Person?", "Who is the most optimistic person?"),
("22", "Wer verbringt am meisten Zeit in der Natur?", "Who spends the most time in nature?"),
("22", "Wer würde am ehesten ein eigenes Unternehmen gründen?", "Who is most likely to start their own business?"),
("22", "Wer ist die abenteuerlustigste Person?", "Who is the most adventurous person?"),
("22", "Wer verbringt am meisten Zeit mit Pflanzen?", "Who spends the most time with plants?"),
("22", "Wer würde am ehesten ein Buch schreiben?", "Who is most likely to write a book?"),
("22", "Wer ist die kreativste Person?", "Who is the most creative person?"),
("22", "Wer verbringt am meisten Zeit mit Freiwilligenarbeit?", "Who spends the most time volunteering?"),
("22", "Wer würde am ehesten eine Fernsehsendung moderieren?", "Who is most likely to host a TV show?"),
("22", "Wer ist die fantasievollste Person?", "Who is the most imaginative person?"),
("22", "Wer verbringt am meisten Zeit im Park?", "Who spends the most time in the park?"),
("22", "Wer würde am ehesten ein neues Hobby beginnen?", "Who is most likely to start a new hobby?"),
("22", "Wer ist die abenteuerlustigste Person?", "Who is the most adventurous person?"),
("22", "Wer verbringt am meisten Zeit mit Tieren?", "Who spends the most time with animals?"),
("22", "Wer würde am ehesten ein neues Instrument lernen?", "Who is most likely to learn a new instrument?"),
("22", "Wer ist die kreative Person?", "Who is the most creative person?"),
("22", "Wer verbringt am meisten Zeit mit Kunst?", "Who spends the most time with art?"),
("22", "Wer würde am ehesten ein Geheimnis bewahren?", "Who is most likely to keep a secret?"),
("22", "Wer ist die verantwortungsvollste Person?", "Who is the most responsible person?"),
("22", "Wer verbringt am meisten Zeit mit Freunden?", "Who spends the most time with friends?"),
("22", "Wer würde am ehesten ein Kunstwerk schaffen?", "Who is most likely to create a piece of art?"),
("22", "Wer ist die geduldigste Person?", "Who is the most patient person?"),
("22", "Wer verbringt am meisten Zeit im Garten?", "Who spends the most time in the garden?"),
("22", "Wer würde am ehesten ein Abenteuer im Dschungel erleben?", "Who is most likely to have an adventure in the jungle?"),
("22", "Wer ist die optimistischste Person?", "Who is the most optimistic person?"),
("22", "Wer verbringt am meisten Zeit mit Haustieren?", "Who spends the most time with pets?"),
("22", "Wer würde am ehesten ein Buch schreiben?", "Who is most likely to write a book?"),
("22", "Wer ist die kreativste Person?", "Who is the most creative person?"),
("22", "Wer verbringt am meisten Zeit mit Pflanzen?", "Who spends the most time with plants?"),
("22", "Wer würde am ehesten ein neues Unternehmen gründen?", "Who is most likely to start a new business?"),
("22", "Wer ist die abenteuerlustigste Person?", "Who is the most adventurous person?"),
("22", "Wer verbringt am meisten Zeit in der Natur?", "Who spends the most time in nature?"),
("22", "Wer würde am ehesten ein neues Hobby beginnen?", "Who is most likely to start a new hobby?"),
("22", "Wer ist die verantwortungsvollste Person?", "Who is the most responsible person?"),
("22", "Wer verbringt am meisten Zeit mit Fotografie?", "Who spends the most time on photography?"),
("22", "Wer würde am ehesten ein Abenteuer im Weltraum erleben?", "Who is most likely to have an adventure in space?"),
("22", "Wer ist die fantasievollste Person?", "Who is the most imaginative person?"),
("22", "Wer verbringt am meisten Zeit mit Haustieren?", "Who spends the most time with pets?"),
("22", "Wer würde am ehesten ein Buch schreiben?", "Who is most likely to write a book?"),
("22", "Wer ist die optimistischste Person?", "Who is the most optimistic person?"),
("22", "Wer verbringt am meisten Zeit im Garten?", "Who spends the most time in the garden?"),
("22", "Wer würde am ehesten ein neues Instrument lernen?", "Who is most likely to learn a new instrument?"),
("22", "Wer ist die kreative Person?", "Who is the most creative person?"),
("22", "Wer verbringt am meisten Zeit mit Kunst?", "Who spends the most time with art?"),
("22", "Wer würde am ehesten ein neues Hobby beginnen?", "Who is most likely to start a new hobby?"),
("22", "Wer ist die verantwortungsvollste Person?", "Who is the most responsible person?"),
("22", "Wer verbringt am meisten Zeit mit Freunden?", "Who spends the most time with friends?"),
("22", "Wer würde am ehesten ein Kunstwerk schaffen?", "Who is most likely to create a piece of art?"),
("22", "Wer ist die geduldigste Person?", "Who is the most patient person?"),
("22", "Wer verbringt am meisten Zeit im Park?", "Who spends the most time in the park?"),
("22", "Wer würde am ehesten ein Abenteuer im Dschungel erleben?", "Who is most likely to have an adventure in the jungle?"),
("22", "Wer ist die optimistischste Person?", "Who is the most optimistic person?"),
("22", "Wer verbringt am meisten Zeit mit Haustieren?", "Who spends the most time with pets?"),
("22", "Wer würde am ehesten ein Buch schreiben?", "Who is most likely to write a book?"),
("22", "Wer ist die kreative Person?", "Who is the most creative person?"),
("22", "Wer verbringt am meisten Zeit mit Pflanzen?", "Who spends the most time with plants?"),
("22", "Wer würde am ehesten ein neues Unternehmen gründen?", "Who is most likely to start a new business?"),
("22", "Wer ist die abenteuerlustigste Person?", "Who is the most adventurous person?"),
("22", "Wer verbringt am meisten Zeit in der Natur?", "Who spends the most time in nature?"),
("22", "Wer würde am ehesten ein neues Hobby beginnen?", "Who is most likely to start a new hobby?"),
("22", "Wer ist die verantwortungsvollste Person?", "Who is the most responsible person?"),
("22", "Wer verbringt am meisten Zeit mit Fotografie?", "Who spends the most time on photography?"),
("22", "Wer würde am ehesten ein Abenteuer im Weltraum erleben?", "Who is most likely to have an adventure in space?"),
("22", "Wer ist die fantasievollste Person?", "Who is the most imaginative person?"),
("22", "Wer verbringt am meisten Zeit mit Haustieren?", "Who spends the most time with pets?"),
("22", "Wer würde am ehesten ein Buch schreiben?", "Who is most likely to write a book?"),
("22", "Wer ist die optimistischste Person?", "Who is the most optimistic person?"),
("22", "Wer verbringt am meisten Zeit im Garten?", "Who spends the most time in the garden?"),
("22", "Wer würde am ehesten ein neues Instrument lernen?", "Who is most likely to learn a new instrument?"),
("22", "Wer ist die kreative Person?", "Who is the most creative person?"),
("22", "Wer verbringt am meisten Zeit mit Kunst?", "Who spends the most time with art?"),
("22", "Wer würde am ehesten ein neues Hobby beginnen?", "Who is most likely to start a new hobby?"),
("22", "Wer ist die verantwortungsvollste Person?", "Who is the most responsible person?"),
("22", "Wer verbringt am meisten Zeit mit Freunden?", "Who spends the most time with friends?"),
("22", "Wer würde am ehesten ein Kunstwerk schaffen?", "Who is most likely to create a piece of art?"),
("22", "Wer ist die geduldigste Person?", "Who is the most patient person?"),
("22", "Wer verbringt am meisten Zeit im Park?", "Who spends the most time in the park?"),
("22", "Wer würde am ehesten ein Abenteuer im Dschungel erleben?", "Who is most likely to have an adventure in the jungle?"),
("22", "Wer ist die optimistischste Person?", "Who is the most optimistic person?"),
("22", "Wer verbringt am meisten Zeit mit Haustieren?", "Who spends the most time with pets?"),
("22", "Wer würde am ehesten ein Buch schreiben?", "Who is most likely to write a book?"),
("22", "Wer ist die kreative Person?", "Who is the most creative person?"),
("22", "Wer verbringt am meisten Zeit mit Pflanzen?", "Who spends the most time with plants?"),
("22", "Wer würde am ehesten ein neues Unternehmen gründen?", "Who is most likely to start a new business?"),
("22", "Wer ist die abenteuerlustigste Person?", "Who is the most adventurous person?"),
("22", "Wer verbringt am meisten Zeit in der Natur?", "Who spends the most time in nature?"),
("22", "Wer würde am ehesten ein neues Hobby beginnen?", "Who is most likely to start a new hobby?"),
("22", "Wer ist die verantwortungsvollste Person?", "Who is the most responsible person?"),
("22", "Wer verbringt am meisten Zeit mit Fotografie?", "Who spends the most time on photography?"),
("22", "Wer würde am ehesten ein Abenteuer im Weltraum erleben?", "Who is most likely to have an adventure in space?"),
("22", "Wer ist die fantasievollste Person?", "Who is the most imaginative person?"),
("22", "Wer verbringt am meisten Zeit mit Haustieren?", "Who spends the most time with pets?"),
("22", "Wer würde am ehesten ein Buch schreiben?", "Who is most likely to write a book?"),
("22", "Wer ist die optimistischste Person?", "Who is the most optimistic person?"),
("22", "Wer verbringt am meisten Zeit im Garten?", "Who spends the most time in the garden?"),
("22", "Wer würde am ehesten ein neues Instrument lernen?", "Who is most likely to learn a new instrument?"),
("22", "Wer ist die kreative Person?", "Who is the most creative person?"),
("22", "Wer verbringt am meisten Zeit mit Kunst?", "Who spends the most time with art?"),
("22", "Wer würde am ehesten ein neues Hobby beginnen?", "Who is most likely to start a new hobby?"),
("22", "Wer ist die verantwortungsvollste Person?", "Who is the most responsible person?"),
("22", "Wer verbringt am meisten Zeit mit Freunden?", "Who spends the most time with friends?"),
("22", "Wer würde am ehesten ein Kunstwerk schaffen?", "Who is most likely to create a piece of art?"),
("22", "Wer ist die geduldigste Person?", "Who is the most patient person?"),
("22", "Wer verbringt am meisten Zeit im Park?", "Who spends the most time in the park?"),
("22", "Wer würde am ehesten ein Abenteuer im Dschungel erleben?", "Who is most likely to have an adventure in the jungle?"),
("22", "Wer ist die optimistischste Person?", "Who is the most optimistic person?"),
("22", "Wer verbringt am meisten Zeit mit Haustieren?", "Who spends the most time with pets?"),
("22", "Wer würde am ehesten ein Buch schreiben?", "Who is most likely to write a book?"),
("22", "Wer ist die kreative Person?", "Who is the most creative person?"),
("22", "Wer verbringt am meisten Zeit mit Pflanzen?", "Who spends the most time with plants?"),
("22", "Wer würde am ehesten ein neues Unternehmen gründen?", "Who is most likely to start a new business?"),
("22", "Wer ist die abenteuerlustigste Person?", "Who is the most adventurous person?"),
("22", "Wer verbringt am meisten Zeit in der Natur?", "Who spends the most time in nature?"),
("22", "Wer würde am ehesten ein neues Hobby beginnen?", "Who is most likely to start a new hobby?"),
("22", "Wer ist die verantwortungsvollste Person?", "Who is the most responsible person?"),
("22", "Wer verbringt am meisten Zeit mit Fotografie?", "Who spends the most time on photography?"),
("22", "Wer würde am ehesten ein Abenteuer im Weltraum erleben?", "Who is most likely to have an adventure in space?"),
("22", "Wer ist die fantasievollste Person?", "Who is the most imaginative person?"),
("22", "Wer verbringt am meisten Zeit mit Haustieren?", "Who spends the most time with pets?"),
("22", "Wer würde am ehesten ein Buch schreiben?", "Who is most likely to write a book?"),
("22", "Wer ist die optimistischste Person?", "Who is the most optimistic person?"),
("22", "Wer verbringt am meisten Zeit im Garten?", "Who spends the most time in the garden?"),
("22", "Wer würde am ehesten ein neues Instrument lernen?", "Who is most likely to learn a new instrument?"),
("22", "Wer ist die kreative Person?", "Who is the most creative person?"),
("22", "Wer verbringt am meisten Zeit mit Kunst?", "Who spends the most time with art?"),
("22", "Wer würde am ehesten ein neues Hobby beginnen?", "Who is most likely to start a new hobby?"),
("22", "Wer ist die verantwortungsvollste Person?", "Who is the most responsible person?"),
("22", "Wer verbringt am meisten Zeit mit Freunden?", "Who spends the most time with friends?"),
("22", "Wer würde am ehesten ein Kunstwerk schaffen?", "Who is most likely to create a piece of art?"),
("22", "Wer ist die geduldigste Person?", "Who is the most patient person?"),
("22", "Wer verbringt am meisten Zeit im Park?", "Who spends the most time in the park?"),
("22", "Wer würde am ehesten ein Abenteuer im Dschungel erleben?", "Who is most likely to have an adventure in the jungle?"),
("22", "Wer ist die optimistischste Person?", "Who is the most optimistic person?"),
("22", "Wer verbringt am meisten Zeit mit Haustieren?", "Who spends the most time with pets?"),
("22", "Wer würde am ehesten ein Buch schreiben?", "Who is most likely to write a book?"),
("22", "Wer ist die kreative Person?", "Who is the most creative person?"),
("22", "Wer verbringt am meisten Zeit mit Pflanzen?", "Who spends the most time with plants?"),
("22", "Wer würde am ehesten ein neues Unternehmen gründen?", "Who is most likely to start a new business?"),
("22", "Wer ist die abenteuerlustigste Person?", "Who is the most adventurous person?"),
("22", "Wer verbringt am meisten Zeit in der Natur?", "Who spends the most time in nature?"),
("22", "Wer würde am ehesten ein neues Hobby beginnen?", "Who is most likely to start a new hobby?"),
("22", "Wer ist die verantwortungsvollste Person?", "Who is the most responsible person?"),
("22", "Wer verbringt am meisten Zeit mit Fotografie?", "Who spends the most time on photography?"),
("22", "Wer würde am ehesten ein Abenteuer im Weltraum erleben?", "Who is most likely to have an adventure in space?"),
("22", "Wer ist die fantasievollste Person?", "Who is the most imaginative person?"),
("22", "Wer verbringt am meisten Zeit mit Haustieren?", "Who spends the most time with pets?"),
("22", "Wer würde am ehesten ein Buch schreiben?", "Who is most likely to write a book?"),
("22", "Wer ist die optimistischste Person?", "Who is the most optimistic person?"),
("22", "Wer verbringt am meisten Zeit im Garten?", "Who spends the most time in the garden?"),
("22", "Wer würde am ehesten ein neues Instrument lernen?", "Who is most likely to learn a new instrument?"),
("22", "Wer ist die kreative Person?", "Who is the most creative person?"),
("22", "Wer verbringt am meisten Zeit mit Kunst?", "Who spends the most time with art?"),
("22", "Wer würde am ehesten ein neues Hobby beginnen?", "Who is most likely to start a new hobby?"),
("22", "Wer ist die verantwortungsvollste Person?", "Who is the most responsible person?"),
("22", "Wer verbringt am meisten Zeit mit Freunden?", "Who spends the most time with friends?"),
("22", "Wer würde am ehesten ein Kunstwerk schaffen?", "Who is most likely to create a piece of art?"),
("22", "Wer ist die geduldigste Person?", "Who is the most patient person?"),
("22", "Wer verbringt am meisten Zeit im Park?", "Who spends the most time in the park?"),
("22", "Wer würde am ehesten ein Abenteuer im Dschungel erleben?", "Who is most likely to have an adventure in the jungle?"),
("22", "Wer ist die optimistischste Person?", "Who is the most optimistic person?"),
("22", "Wer verbringt am meisten Zeit mit Haustieren?", "Who spends the most time with pets?"),
("22", "Wer würde am ehesten ein Buch schreiben?", "Who is most likely to write a book?"),
("22", "Wer ist die kreative Person?", "Who is the most creative person?"),
("22", "Wer verbringt am meisten Zeit mit Pflanzen?", "Who spends the most time with plants?"),
("22", "Wer würde am ehesten ein neues Unternehmen gründen?", "Who is most likely to start a new business?"),
("22", "Wer ist die abenteuerlustigste Person?", "Who is the most adventurous person?"),
("22", "Wer verbringt am meisten Zeit in der Natur?", "Who spends the most time in nature?"),
("22", "Wer würde am ehesten ein neues Hobby beginnen?", "Who is most likely to start a new hobby?"),
("22", "Wer ist die verantwortungsvollste Person?", "Who is the most responsible person?"),
("22", "Wer verbringt am meisten Zeit mit Fotografie?", "Who spends the most time on photography?"),
("22", "Wer würde am ehesten ein Abenteuer im Weltraum erleben?", "Who is most likely to have an adventure in space?"),
("22", "Wer ist die fantasievollste Person?", "Who is the most imaginative person?"),
("22", "Wer verbringt am meisten Zeit mit Haustieren?", "Who spends the most time with pets?"),
("22", "Wer würde am ehesten ein Buch schreiben?", "Who is most likely to write a book?"),
("22", "Wer ist die optimistischste Person?", "Who is the most optimistic person?"),