INSERT INTO game_klassiker_questions (fk_pool, content, content_english, drunk_level, exposure_level, bool_drink) VALUES
("2", "Was ist das peinlichste Lied in deiner Playlist?", "What is the most embarrassing song on your playlist?", "1", "4", "0"),
("2", "Was ist die lustigste Ausrede, die du jemals benutzt hast, um nicht zur Arbeit oder Schule zu gehen?", "What is the funniest excuse you ever used to skip work or school?", "1", "5", "0"),
("2", "Wer aus der Runde würde am ehesten einen Tag ohne Internet überleben?", "Who in the group would be most likely to survive a day without the internet?", "0", "3", "0"),
("2", "Was war das lustigste Missverständnis, das du jemals hattest?", "What was the funniest misunderstanding you ever had?", "0", "4", "0"),
("2", "Wenn du ein Tier sein könntest, welches wärst du und warum?", "If you could be an animal, which one would you be and why?", "0", "2", "0"),
("2", "Was ist dein unnötigstes Talent?", "What is your most useless talent?", "1", "3", "0"),
("2", "Wer ist die schlechteste Lügnerin in dieser Runde?", "Who is the worst liar in this group?", "1", "4", "0"),
("2", "Was war dein lustigster Betrunkenerlebnis?", "What was your funniest drunk experience?", "5", "7", "0"),
("2", "Wenn du in einem Film leben könntest, welcher wäre es?", "If you could live in a movie, which one would it be?", "0", "1", "0"),
("2", "Was war das merkwürdigste Essen, das du jemals probiert hast?", "What is the weirdest food you have ever tried?", "0", "3", "0"),
("2", "Wer aus der Runde hätte die besten Chancen, in einer Zombie-Apokalypse zu überleben?", "Who in the group would have the best chances of surviving a zombie apocalypse?", "0", "2", "0"),
("2", "Was ist dein geheimes Laster?", "What is your guilty pleasure?", "1", "4", "0"),
("2", "Wer ist die mutigste Person, die du kennst?", "Who is the bravest person you know?", "0", "3", "0"),
("2", "Was war der verrückteste Traum, den du jemals hattest?", "What is the craziest dream you ever had?", "0", "5", "0"),
("2", "Wer aus der Runde würde am ehesten in einer Reality-Show mitmachen?", "Who in the group would most likely participate in a reality show?", "1", "4", "0"),
("2", "Was ist das teuerste, das du jemals kaputt gemacht hast?", "What is the most expensive thing you ever broke?", "0", "5", "0"),
("2", "Was war dein peinlichstes Date?", "What was your most embarrassing date?", "1", "7", "0"),
("2", "Wer aus der Runde hat den seltsamsten Spitznamen?", "Who in the group has the weirdest nickname?", "0", "4", "0"),
("2", "Wenn du einen Tag das Leben einer anderen Person leben könntest, wer wäre das?", "If you could live one day as another person, who would it be?", "0", "2", "0"),
("2", "Was ist die dümmste Verletzung, die du jemals hattest?", "What is the dumbest injury you ever had?", "1", "5", "0"),
("2", "Wer aus der Runde würde am ehesten einen Kochwettbewerb gewinnen?", "Who in the group would most likely win a cooking competition?", "0", "2", "0"),
("2", "Was war das lustigste Geschenk, das du jemals erhalten hast?", "What is the funniest gift you have ever received?", "1", "3", "0"),
("2", "Was ist deine verrückteste Angewohnheit?", "What is your weirdest habit?", "1", "4", "0"),
("2", "Wer aus der Runde wäre der schlechteste Geheimagent?", "Who in the group would be the worst secret agent?", "0", "4", "0"),
("2", "Was war das unangenehmste Outfit, das du jemals getragen hast?", "What is the most uncomfortable outfit you have ever worn?", "1", "6", "0"),
("2", "Wer aus der Runde würde am ehesten zu spät zur eigenen Hochzeit kommen?", "Who in the group would most likely be late to their own wedding?", "0", "3", "0"),
("2", "Was ist das absurdeste Gerücht, das du jemals gehört hast?", "What is the most absurd rumor you have ever heard?", "0", "4", "0"),
("2", "Wer aus der Runde hat den schlechtesten Musikgeschmack?", "Who in the group has the worst taste in music?", "1", "5", "0"),
("2", "Was ist die seltsamste Sache, die du je gekauft hast?", "What is the weirdest thing you have ever bought?", "1", "4", "0"),
("2", "Wer aus der Runde würde am ehesten Präsident werden?", "Who in the group would most likely become president?", "0", "2", "0"),
("2", "Was war das peinlichste Foto, das von dir existiert?", "What is the most embarrassing photo of you that exists?", "1", "7", "0"),
("2", "Wer aus der Runde kann die meisten Witze erzählen?", "Who in the group can tell the most jokes?", "1", "3", "0"),
("2", "Was war dein seltsamstes Treffen mit einer berühmten Person?", "What was your weirdest encounter with a famous person?", "0", "5", "0"),
("2", "Wer aus der Runde hätte die besten Chancen, in einem Horrorfilm zu überleben?", "Who in the group would have the best chances of surviving in a horror movie?", "0", "3", "0"),
("2", "Was ist das Lustigste, das dir je auf der Arbeit oder in der Schule passiert ist?", "What is the funniest thing that ever happened to you at work or school?", "1", "5", "0"),
("2", "Wer aus der Runde würde am ehesten einen Tag im Bett verbringen?", "Who in the group would most likely spend a day in bed?", "0", "2", "0"),
("2", "Was war der schlimmste Haarschnitt, den du jemals hattest?", "What is the worst haircut you have ever had?", "1", "6", "0"),
("2", "Wer aus der Runde hat das schlechteste Gedächtnis?", "Who in the group has the worst memory?", "1", "3", "0"),
("2", "Was ist das Unnötigste, das du jemals gekauft hast?", "What is the most useless thing you have ever bought?", "1", "4", "0"),
("2", "Wer aus der Runde kann am besten tanzen?", "Who in the group is the best dancer?", "0", "2", "0"),
("2", "Was war der seltsamste Anruf, den du jemals bekommen hast?", "What is the weirdest phone call you ever received?", "0", "5", "0"),
("2", "Wer aus der Runde würde am ehesten in einem Zirkus arbeiten?", "Who in the group would most likely work in a circus?", "0", "3", "0"),
("2", "Was ist das absurdeste Video, das du jemals gesehen hast?", "What is the most absurd video you have ever seen?", "0", "4", "0"),
("2", "Wer aus der Runde hat die beste Lache?", "Who in the group has the best laugh?", "0", "2", "0"),
("2", "Was war der schlechteste Film, den du jemals gesehen hast?", "What is the worst movie you have ever seen?", "0", "3", "0"),
("2", "Wer aus der Runde würde am ehesten einen Marathon laufen?", "Who in the group would most likely run a marathon?", "0", "2", "0"),
("2", "Was ist das ungewöhnlichste Kompliment, das du jemals bekommen hast?", "What is the most unusual compliment you have ever received?", "0", "4", "0"),
("2", "Wer aus der Runde kann am besten singen?", "Who in the group can sing the best?", "0", "2", "0"),
("2", "Was war das verrückteste Spiel, das du jemals gespielt hast?", "What is the craziest game you have ever played?", "1", "3", "0"),
("2", "Wer aus der Runde würde am ehesten bei einer Talentshow auftreten?", "Who in the group would most likely perform in a talent show?", "0", "3", "0"),
("2", "Was war das dümmste Missgeschick, das dir jemals passiert ist?", "What is the dumbest mishap that ever happened to you?", "1", "5", "0"),
("2", "Wer aus der Runde würde am ehesten einen Monat ohne Social Media aushalten?", "Who in the group would most likely survive a month without social media?", "0", "2", "0"),
("2", "Was war die peinlichste Nachricht, die du jemals verschickt hast?", "What is the most embarrassing message you ever sent?", "1", "7", "0"),
("2", "Wer aus der Runde hat die meisten unnötigen Apps auf dem Handy?", "Who in the group has the most useless apps on their phone?", "1", "4", "0"),
("2", "Was war das lustigste Missgeschick, das dir jemals beim Kochen passiert ist?", "What is the funniest mishap that ever happened to you while cooking?", "1", "5", "0"),
("2", "Wer aus der Runde würde am ehesten ein geheimes Doppelleben führen?", "Who in the group would most likely live a secret double life?", "0", "3", "0"),
("2", "Was war das verrückteste, das du jemals in einer Beziehung gemacht hast?", "What is the craziest thing you ever did in a relationship?", "1", "6", "0"),
("2", "Wer aus der Runde würde am ehesten bei einer Karaoke-Nacht auftreten?", "Who in the group would most likely perform at a karaoke night?", "1", "3", "0"),
("2", "Was ist die unnötigste Fähigkeit, die du jemals gelernt hast?", "What is the most useless skill you ever learned?", "1", "4", "0"),
("2", "Wer aus der Runde würde am ehesten eine Weltreise machen?", "Who in the group would most likely go on a world tour?", "0", "2", "0"),
("2", "Was war das unangenehmste Missgeschick, das dir jemals beim Sport passiert ist?", "What is the most embarrassing mishap that ever happened to you while playing sports?", "1", "6", "0"),
("2", "Wer aus der Runde hat die besten Geschichten auf Lager?", "Who in the group has the best stories to tell?", "0", "2", "0"),
("2", "Was ist die ungewöhnlichste Sache, die du jemals gegessen hast?", "What is the most unusual thing you have ever eaten?", "0", "4", "0"),
("2", "Wer aus der Runde würde am ehesten ein Buch schreiben?", "Who in the group would most likely write a book?", "0", "3", "0"),
("2", "Was war das peinlichste Gespräch, das du jemals belauscht hast?", "What is the most embarrassing conversation you ever eavesdropped on?", "1", "7", "0"),
("2", "Wer aus der Runde hat den besten Modestil?", "Who in the group has the best fashion style?", "0", "2", "0"),
("2", "Was war das seltsamste Geschenk, das du jemals bekommen hast?", "What is the weirdest gift you have ever received?", "1", "4", "0"),
("2", "Wer aus der Runde würde am ehesten einen Tag ohne zu sprechen verbringen?", "Who in the group would most likely spend a day without speaking?", "0", "2", "0"),
("2", "Was ist die lustigste Show, die du jemals gesehen hast?", "What is the funniest show you have ever seen?", "0", "3", "0"),
("2", "Wer aus der Runde würde am ehesten eine verrückte Haarfarbe ausprobieren?", "Who in the group would most likely try a crazy hair color?", "0", "3", "0"),
("2", "Was war das absurdeste Missverständnis, das du jemals hattest?", "What is the most absurd misunderstanding you ever had?", "0", "4", "0"),
("2", "Wer aus der Runde würde am ehesten in einer Band spielen?", "Who in the group would most likely play in a band?", "0", "2", "0"),
("2", "Was war das ungewöhnlichste Erlebnis, das du jemals hattest?", "What is the most unusual experience you ever had?", "0", "5", "0"),
("2", "Wer aus der Runde würde am ehesten in einem Werbespot auftreten?", "Who in the group would most likely appear in a commercial?", "0", "3", "0"),
("2", "Was ist das lustigste Buch, das du jemals gelesen hast?", "What is the funniest book you have ever read?", "0", "3", "0"),
("2", "Wer aus der Runde würde am ehesten in einem anderen Land leben?", "Who in the group would most likely live in another country?", "0", "2", "0"),
("2", "Was war der unangenehmste Moment, den du jemals auf einer Party erlebt hast?", "What is the most embarrassing moment you ever had at a party?", "5", "7", "0"),
("2", "Wer aus der Runde hat das interessanteste Hobby?", "Who in the group has the most interesting hobby?", "0", "2", "0"),
("2", "Was ist das ungewöhnlichste Geräusch, das du jemals gehört hast?", "What is the most unusual sound you have ever heard?", "0", "4", "0"),
("2", "Wer aus der Runde würde am ehesten eine neue Sportart ausprobieren?", "Who in the group would most likely try a new sport?", "0", "2", "0"),
("2", "Was war das peinlichste Missgeschick, das dir jemals beim Einkaufen passiert ist?", "What is the most embarrassing mishap that ever happened to you while shopping?", "1", "6", "0"),
("2", "Wer aus der Runde würde am ehesten einen Stand-up-Comedy-Auftritt wagen?", "Who in the group would most likely try a stand-up comedy performance?", "1", "4", "0"),
("2", "Was ist das absurdeste Kostüm, das du jemals getragen hast?", "What is the most absurd costume you have ever worn?", "1", "6", "0"),
("2", "Wer aus der Runde würde am ehesten ein Restaurant eröffnen?", "Who in the group would most likely open a restaurant?", "0", "2", "0"),
("2", "Was war das lustigste Video, das du jemals gesehen hast?", "What is the funniest video you have ever seen?", "0", "3", "0"),
("2", "Wer aus der Runde würde am ehesten ein geheimes Tagebuch führen?", "Who in the group would most likely keep a secret diary?", "0", "3", "0"),
("2", "Was war das seltsamste Kompliment, das du jemals bekommen hast?", "What is the weirdest compliment you have ever received?", "0", "4", "0"),
("2", "Wer aus der Runde würde am ehesten eine verrückte Wette eingehen?", "Who in the group would most likely make a crazy bet?", "1", "3", "0"),
("2", "Was war das peinlichste, das dir jemals beim Autofahren passiert ist?", "What is the most embarrassing thing that ever happened to you while driving?", "1", "6", "0"),
("2", "Wer aus der Runde würde am ehesten einen Tag im Schlafanzug verbringen?", "Who in the group would most likely spend a day in pajamas?", "0", "2", "0"),
("2", "Was war der lustigste Moment, den du jemals mit deiner Familie hattest?", "What is the funniest moment you ever had with your family?", "0", "5", "0");
