INSERT INTO game_klassiker_questions (fk_pool, content, content_english, drunk_level, exposure_level, bool_drink) VALUES
("2", "Was war das absurdeste Outfit, das du jemals in der Öffentlichkeit getragen hast?", "What is the most absurd outfit you have ever worn in public?", "1", "6", "0"),
("2", "Wer aus der Runde würde am ehesten einen Tag ohne Elektronik überstehen?", "Who in the group would most likely survive a day without electronics?", "0", "2", "0"),
("2", "Was war dein lustigster Moment im Fitnessstudio?", "What is your funniest moment at the gym?", "1", "5", "0"),
("2", "Wer aus der Runde hat die kreativsten Ausreden?", "Who in the group has the most creative excuses?", "0", "3", "0"),
("2", "Was ist die seltsamste Sache, die du jemals verloren hast?", "What is the weirdest thing you ever lost?", "0", "4", "0"),
("2", "Wer aus der Runde hat die beste Handschrift?", "Who in the group has the best handwriting?", "0", "2", "0"),
("2", "Was war das verrückteste, das dir jemals im Urlaub passiert ist?", "What is the craziest thing that ever happened to you on vacation?", "1", "5", "0"),
("2", "Wer aus der Runde würde am ehesten einen Tanzwettbewerb gewinnen?", "Who in the group would most likely win a dance competition?", "0", "3", "0"),
("2", "Was ist das lustigste Buch, das du jemals gelesen hast?", "What is the funniest book you have ever read?", "0", "3", "0"),
("2", "Wer aus der Runde würde am ehesten eine neue Sprache lernen?", "Who in the group would most likely learn a new language?", "0", "2", "0"),
("2", "Was war das seltsamste Gespräch, das du jemals belauscht hast?", "What is the weirdest conversation you ever overheard?", "0", "4", "0"),
("2", "Wer aus der Runde hat die meisten lustigen Spitznamen?", "Who in the group has the most funny nicknames?", "0", "3", "0"),
("2", "Was ist das ungewöhnlichste Haustier, das du jemals hattest?", "What is the most unusual pet you ever had?", "1", "4", "0"),
("2", "Wer aus der Runde würde am ehesten einen Extremsport ausprobieren?", "Who in the group would most likely try an extreme sport?", "0", "3", "0"),
("2", "Was war das peinlichste Geschenk, das du jemals erhalten hast?", "What is the most embarrassing gift you have ever received?", "1", "6", "0"),
("2", "Wer aus der Runde hat den besten Sinn für Humor?", "Who in the group has the best sense of humor?", "0", "2", "0"),
("2", "Was ist das absurdeste Accessoire, das du jemals getragen hast?", "What is the most absurd accessory you have ever worn?", "1", "5", "0"),
("2", "Wer aus der Runde würde am ehesten in einem Musikvideo mitspielen?", "Who in the group would most likely appear in a music video?", "0", "3", "0"),
("2", "Was war der seltsamste Albtraum, den du jemals hattest?", "What is the weirdest nightmare you ever had?", "0", "5", "0"),
("2", "Wer aus der Runde hat die beste Sammlung von etwas?", "Who in the group has the best collection of something?", "0", "3", "0"),
("2", "Was ist die ungewöhnlichste Fähigkeit, die du jemals gelernt hast?", "What is the most unusual skill you ever learned?", "1", "4", "0"),
("2", "Wer aus der Runde würde am ehesten einen Science-Fiction-Roman schreiben?", "Who in the group would most likely write a science fiction novel?", "0", "3", "0"),
("2", "Was war das lustigste Kostüm, das du jemals getragen hast?", "What is the funniest costume you ever wore?", "1", "5", "0"),
("2", "Wer aus der Runde würde am ehesten einen Tag ohne Schuhe verbringen?", "Who in the group would most likely spend a day without shoes?", "0", "2", "0"),
("2", "Was ist das absurdeste Kompliment, das du jemals bekommen hast?", "What is the most absurd compliment you ever received?", "0", "4", "0"),
("2", "Wer aus der Runde würde am ehesten einen Tag als Detektiv verbringen?", "Who in the group would most likely spend a day as a detective?", "0", "3", "0"),
("2", "Was war das ungewöhnlichste Hobby, das du jemals hattest?", "What is the most unusual hobby you ever had?", "1", "4", "0"),
("2", "Wer aus der Runde würde am ehesten einen Tag als Straßenkünstler verbringen?", "Who in the group would most likely spend a day as a street performer?", "0", "3", "0"),
("2", "Was war das peinlichste Date, das du jemals hattest?", "What is the most embarrassing date you ever had?", "1", "7", "0"),
("2", "Wer aus der Runde würde am ehesten eine Woche ohne Internet überleben?", "Who in the group would most likely survive a week without the internet?", "0", "2", "0"),
("2", "Was ist das ungewöhnlichste Getränk, das du jemals probiert hast?", "What is the most unusual drink you ever tried?", "1", "4", "0"),
("2", "Wer aus der Runde würde am ehesten in einem Kochbuch erscheinen?", "Who in the group would most likely appear in a cookbook?", "0", "3", "0"),
("2", "Was war das absurdeste Missverständnis, das du jemals hattest?", "What is the most absurd misunderstanding you ever had?", "0", "4", "0"),
("2", "Wer aus der Runde würde am ehesten einen Tag als Clown arbeiten?", "Who in the group would most likely spend a day as a clown?", "0", "3", "0"),
("2", "Was war das seltsamste Geschenk, das du jemals bekommen hast?", "What is the weirdest gift you ever received?", "1", "4", "0"),
("2", "Wer aus der Runde hat die beste Vorstellungskraft?", "Who in the group has the best imagination?", "0", "2", "0"),
("2", "Was war das lustigste Missgeschick, das dir jemals beim Kochen passiert ist?", "What is the funniest mishap that ever happened to you while cooking?", "1", "5", "0"),
("2", "Wer aus der Runde würde am ehesten in einem Werbespot mitspielen?", "Who in the group would most likely appear in a commercial?", "0", "3", "0"),
("2", "Was ist die absurdeste Sache, die du jemals gegessen hast?", "What is the most absurd thing you ever ate?", "1", "4", "0"),
("2", "Wer aus der Runde würde am ehesten einen Tag im Zoo verbringen?", "Who in the group would most likely spend a day at the zoo?", "0", "2", "0"),
("2", "Was war das seltsamste Kompliment, das du jemals bekommen hast?", "What is the weirdest compliment you ever received?", "0", "4", "0"),
("2", "Wer aus der Runde würde am ehesten einen Tag als Straßenmusiker verbringen?", "Who in the group would most likely spend a day as a street musician?", "0", "3", "0"),
("2", "Was war das absurdeste Erlebnis, das du jemals hattest?", "What is the most absurd experience you ever had?", "1", "5", "0"),
("2", "Wer aus der Runde würde am ehesten einen Tag ohne Reden verbringen?", "Who in the group would most likely spend a day without talking?", "0", "2", "0"),
("2", "Was war das ungewöhnlichste Essen, das du jemals probiert hast?", "What is the most unusual food you ever tried?", "1", "4", "0"),
("2", "Wer aus der Runde würde am ehesten einen Tag als Lehrer verbringen?", "Who in the group would most likely spend a day as a teacher?", "0", "3", "0"),
("2", "Was war das seltsamste Geschenk, das du jemals gemacht hast?", "What is the weirdest gift you ever gave?", "1", "4", "0"),
("2", "Wer aus der Runde hat den besten Sinn für Abenteuer?", "Who in the group has the best sense of adventure?", "0", "2", "0"),
("2", "Was war das lustigste Missverständnis, das du jemals hattest?", "What is the funniest misunderstanding you ever had?", "0", "4", "0"),
("2", "Wer aus der Runde würde am ehesten in einem Theaterstück mitspielen?", "Who in the group would most likely perform in a play?", "0", "3", "0"),
("2", "Was war das absurdeste, das dir jemals im Urlaub passiert ist?", "What is the most absurd thing that ever happened to you on vacation?", "1", "5", "0"),
("2", "Wer aus der Runde würde am ehesten einen Tag ohne Sprechen verbringen?", "Who in the group would most likely spend a day without speaking?", "0", "2", "0"),
("2", "Was war das ungewöhnlichste Getränk, das du jemals probiert hast?", "What is the most unusual drink you ever tried?", "1", "4", "0"),
("2", "Wer aus der Runde würde am ehesten in einem Kunstwettbewerb gewinnen?", "Who in the group would most likely win an art competition?", "0", "3", "0"),
("2", "Was war das seltsamste Kompliment, das du jemals bekommen hast?", "What is the weirdest compliment you ever received?", "0", "4", "0"),
("2", "Wer aus der Runde würde am ehesten einen Tag als Fotograf verbringen?", "Who in the group would most likely spend a day as a photographer?", "0", "3", "0"),
("2", "Was war das absurdeste Erlebnis, das du jemals hattest?", "What is the most absurd experience you ever had?", "1", "5", "0"),
("2", "Wer aus der Runde würde am ehesten einen Tag ohne Elektronik überleben?", "Who in the group would most likely survive a day without electronics?", "0", "2", "0"),
("2", "Was war das ungewöhnlichste Haustier, das du jemals hattest?", "What is the most unusual pet you ever had?", "1", "4", "0"),
("2", "Wer aus der Runde würde am ehesten in einem Modewettbewerb gewinnen?", "Who in the group would most likely win a fashion competition?", "0", "3", "0"),
("2", "Was war das seltsamste Geschenk, das du jemals bekommen hast?", "What is the weirdest gift you ever received?", "1", "4", "0"),
("2", "Wer aus der Runde hat den besten Sinn für Humor?", "Who in the group has the best sense of humor?", "0", "2", "0"),
("2", "Was war das lustigste Missverständnis, das du jemals hattest?", "What is the funniest misunderstanding you ever had?", "0", "4", "0"),
("2", "Wer aus der Runde würde am ehesten in einem Musikwettbewerb gewinnen?", "Who in the group would most likely win a music competition?", "0", "3", "0"),
("2", "Was war das absurdeste Erlebnis, das du jemals im Urlaub hattest?", "What is the most absurd experience you ever had on vacation?", "1", "5", "0"),
("2", "Wer aus der Runde würde am ehesten einen Tag ohne Reden verbringen?", "Who in the group would most likely spend a day without talking?", "0", "2", "0"),
("2", "Was war das ungewöhnlichste Getränk, das du jemals probiert hast?", "What is the most unusual drink you ever tried?", "1", "4", "0"),
("2", "Wer aus der Runde würde am ehesten in einem Sportwettbewerb gewinnen?", "Who in the group would most likely win a sports competition?", "0", "3", "0"),
("2", "Was war das seltsamste Kompliment, das du jemals bekommen hast?", "What is the weirdest compliment you ever received?", "0", "4", "0"),
("2", "Wer aus der Runde würde am ehesten einen Tag als Detektiv verbringen?", "Who in the group would most likely spend a day as a detective?", "0", "3", "0"),
("2", "Was war das absurdeste, das dir jemals im Urlaub passiert ist?", "What is the most absurd thing that ever happened to you on vacation?", "1", "5", "0"),
("2", "Wer aus der Runde würde am ehesten einen Tag ohne Elektronik überleben?", "Who in the group would most likely survive a day without electronics?", "0", "2", "0"),
("2", "Was war das ungewöhnlichste Haustier, das du jemals hattest?", "What is the most unusual pet you ever had?", "1", "4", "0"),
("2", "Wer aus der Runde würde am ehesten in einem Kochwettbewerb gewinnen?", "Who in the group would most likely win a cooking competition?", "0", "3", "0"),
("2", "Was war das seltsamste Geschenk, das du jemals gemacht hast?", "What is the weirdest gift you ever gave?", "1", "4", "0"),
("2", "Wer aus der Runde hat den besten Sinn für Abenteuer?", "Who in the group has the best sense of adventure?", "0", "2", "0"),
("2", "Was war das lustigste Missverständnis, das du jemals hattest?", "What is the funniest misunderstanding you ever had?", "0", "4", "0"),
("2", "Wer aus der Runde würde am ehesten in einem Theaterstück mitspielen?", "Who in the group would most likely perform in a play?", "0", "3", "0"),
("2", "Was war das absurdeste, das dir jemals im Urlaub passiert ist?", "What is the most absurd thing that ever happened to you on vacation?", "1", "5", "0"),
("2", "Wer aus der Runde würde am ehesten einen Tag ohne Sprechen verbringen?", "Who in the group would most likely spend a day without speaking?", "0", "2", "0"),
("2", "Was war das ungewöhnlichste Getränk, das du jemals probiert hast?", "What is the most unusual drink you ever tried?", "1", "4", "0"),
("2", "Wer aus der Runde würde am ehesten in einem Kunstwettbewerb gewinnen?", "Who in the group would most likely win an art competition?", "0", "3", "0"),
("2", "Was war das seltsamste Kompliment, das du jemals bekommen hast?", "What is the weirdest compliment you ever received?", "0", "4", "0"),
("2", "Wer aus der Runde würde am ehesten einen Tag als Fotograf verbringen?", "Who in the group would most likely spend a day as a photographer?", "0", "3", "0"),
("2", "Was war das absurdeste Erlebnis, das du jemals hattest?", "What is the most absurd experience you ever had?", "1", "5", "0"),
("2", "Wer aus der Runde würde am ehesten einen Tag ohne Elektronik überleben?", "Who in the group would most likely survive a day without electronics?", "0", "2", "0"),
("2", "Was war das ungewöhnlichste Haustier, das du jemals hattest?", "What is the most unusual pet you ever had?", "1", "4", "0"),
("2", "Wer aus der Runde würde am ehesten in einem Modewettbewerb gewinnen?", "Who in the group would most likely win a fashion competition?", "0", "3", "0"),
("2", "Was war das seltsamste Geschenk, das du jemals bekommen hast?", "What is the weirdest gift you ever received?", "1", "4", "0"),
("2", "Wer aus der Runde hat den besten Sinn für Humor?", "Who in the group has the best sense of humor?", "0", "2", "0"),
("2", "Was war das lustigste Missverständnis, das du jemals hattest?", "What is the funniest misunderstanding you ever had?", "0", "4", "0"),
("2", "Wer aus der Runde würde am ehesten in einem Musikwettbewerb gewinnen?", "Who in the group would most likely win a music competition?", "0", "3", "0"),
("2", "Was war das absurdeste Erlebnis, das du jemals im Urlaub hattest?", "What is the most absurd experience you ever had on vacation?", "1", "5", "0");
