INSERT INTO game_klassiker_questions (fk_pool, content, content_english, drunk_level, exposure_level, bool_drink) VALUES
("4", "Ich habe noch nie aus Versehen die gleiche Nachricht zweimal an die gleiche Person geschickt.", "I have never accidentally sent the same message twice to the same person.", "2", "3", "0"),
("4", "Ich bin noch nie eingeschlafen, während ich einen Film im Kino geschaut habe.", "I have never fallen asleep while watching a movie in the cinema.", "3", "2", "0"),
("4", "Ich habe noch nie jemanden versehentlich mit dem falschen Namen angesprochen.", "I have never accidentally called someone by the wrong name.", "2", "5", "0"),
("4", "Ich bin noch nie beim Tanzen auf der Tanzfläche gestolpert.", "I have never tripped on the dance floor while dancing.", "4", "6", "0"),
("4", "Ich habe noch nie in der Öffentlichkeit laut gesungen.", "I have never sung loudly in public.", "5", "4", "0"),
("4", "Ich bin noch nie aus einem Restaurant gegangen, ohne zu bezahlen.", "I have never left a restaurant without paying.", "8", "7", "0"),
("4", "Ich habe noch nie jemanden auf Social Media gestalkt.", "I have never stalked someone on social media.", "1", "4", "0"),
("4", "Ich bin noch nie in der Schule eingeschlafen.", "I have never fallen asleep at school.", "3", "3", "0"),
("4", "Ich habe noch nie etwas im Internet bestellt und es sofort bereut.", "I have never ordered something online and regretted it immediately.", "2", "2", "0"),
("4", "Ich habe noch nie mein Handy in die Toilette fallen lassen.", "I have never dropped my phone in the toilet.", "6", "8", "0"),
("4", "Ich bin noch nie in einen falschen Zug oder Bus eingestiegen.", "I have never gotten on the wrong train or bus.", "3", "5", "0"),
("4", "Ich habe noch nie einen ganzen Tag im Schlafanzug verbracht.", "I have never spent an entire day in pajamas.", "2", "2", "0"),
("4", "Ich habe noch nie ein Geheimnis weiter erzählt, das mir anvertraut wurde.", "I have never told a secret that was entrusted to me.", "3", "6", "0"),
("4", "Ich bin noch nie auf einer Party eingeschlafen.", "I have never fallen asleep at a party.", "5", "4", "0"),
("4", "Ich habe noch nie unter der Dusche gesungen.", "I have never sung in the shower.", "2", "1", "0"),
("4", "Ich bin noch nie zu spät zu einem Vorstellungsgespräch gekommen.", "I have never been late to a job interview.", "4", "7", "0"),
("4", "Ich habe noch nie ein peinliches Foto von mir ins Internet gestellt.", "I have never posted an embarrassing photo of myself online.", "3", "6", "0"),
("4", "Ich bin noch nie mit der Kleidung meines Geschwisters rausgegangen, ohne dass sie es wussten.", "I have never gone out wearing my sibling's clothes without them knowing.", "4", "4", "0"),
("4", "Ich habe noch nie Karaoke gesungen.", "I have never sung karaoke.", "4", "5", "0"),
("4", "Ich bin noch nie wegen einer Lüge erwischt worden.", "I have never been caught in a lie.", "4", "6", "0"),
("4", "Ich habe noch nie Essen von jemand anderem aus dem Kühlschrank genommen, ohne zu fragen.", "I have never taken someone else's food from the fridge without asking.", "5", "6", "0"),
("4", "Ich bin noch nie zu einem Date zu spät gekommen.", "I have never been late to a date.", "3", "5", "0"),
("4", "Ich habe noch nie etwas Wertvolles kaputt gemacht und es versteckt.", "I have never broken something valuable and hidden it.", "5", "7", "0"),
("4", "Ich bin noch nie wegen zu lauter Musik von den Nachbarn beschwert worden.", "I have never been complained about by neighbors for playing music too loud.", "4", "3", "0"),
("4", "Ich habe noch nie ein peinliches Missverständnis erlebt.", "I have never experienced an embarrassing misunderstanding.", "2", "5", "0"),
("4", "Ich bin noch nie von einem Fahrrad gefallen.", "I have never fallen off a bicycle.", "3", "4", "0"),
("4", "Ich habe noch nie versehentlich einen Freund oder eine Freundin verletzt.", "I have never accidentally hurt a friend.", "4", "6", "0"),
("4", "Ich bin noch nie versehentlich eingeschlossen worden.", "I have never been accidentally locked in.", "4", "6", "0"),
("4", "Ich habe noch nie einen falschen Weg genommen und es erst spät bemerkt.", "I have never taken a wrong turn and noticed it too late.", "3", "4", "0"),
("4", "Ich bin noch nie versehentlich im Pyjama zum Einkaufen gegangen.", "I have never accidentally gone shopping in my pajamas.", "5", "8", "0"),
("4", "Ich habe noch nie vergessen, dass ich den Herd angelassen habe.", "I have never forgotten that I left the stove on.", "4", "5", "0"),
("4", "Ich bin noch nie in einem Meeting eingeschlafen.", "I have never fallen asleep in a meeting.", "4", "6", "0"),
("4", "Ich habe noch nie beim Spielen eines Spiels betrogen.", "I have never cheated while playing a game.", "3", "6", "0"),
("4", "Ich bin noch nie in der Öffentlichkeit gestolpert und hingefallen.", "I have never tripped and fallen in public.", "4", "7", "0"),
("4", "Ich habe noch nie meine Tasche irgendwo vergessen.", "I have never forgotten my bag somewhere.", "4", "5", "0"),
("4", "Ich bin noch nie aufgewacht und wusste nicht, wo ich war.", "I have never woken up and not known where I was.", "6", "7", "0"),
("4", "Ich habe noch nie meine Schlüssel verloren.", "I have never lost my keys.", "4", "5", "0"),
("4", "Ich bin noch nie beim Lachen aus Versehen gerülpst.", "I have never accidentally burped while laughing.", "4", "6", "0"),
("4", "Ich habe noch nie eine Woche lang denselben Pulli getragen.", "I have never worn the same sweater for a week.", "3", "5", "0"),
("4", "Ich bin noch nie beim Sprechen von der Bühne gefallen.", "I have never fallen off the stage while speaking.", "5", "8", "0"),
("4", "Ich habe noch nie etwas Peinliches ins falsche Chatfenster geschrieben.", "I have never sent something embarrassing to the wrong chat window.", "4", "7", "0"),
("4", "Ich bin noch nie ohne Schuhe nach Hause gekommen.", "I have never come home without shoes.", "6", "8", "0"),
("4", "Ich habe noch nie in der Öffentlichkeit laut gefurzt.", "I have never farted loudly in public.", "6", "9", "0"),
("4", "Ich bin noch nie durch eine Glastür gelaufen.", "I have never walked into a glass door.", "4", "7", "0"),
("4", "Ich habe noch nie eine falsche Adresse angegeben.", "I have never given a wrong address.", "2", "4", "0"),
("4", "Ich bin noch nie mit offenen Schnürsenkeln gestolpert.", "I have never tripped with my shoelaces untied.", "3", "5", "0"),
("4", "Ich habe noch nie versehentlich jemandem die Tür ins Gesicht geschlagen.", "I have never accidentally slammed the door in someone's face.", "4", "6", "0"),
("4", "Ich bin noch nie in der Öffentlichkeit hingefallen und habe es sofort bereut.", "I have never fallen in public and immediately regretted it.", "4", "7", "0"),
("4", "Ich habe noch nie etwas Verbotenes gemacht und bin erwischt worden.", "I have never done something forbidden and got caught.", "5", "8", "0"),
("4", "Ich bin noch nie in der falschen Klasse gewesen.", "I have never been in the wrong class.", "2", "4", "0"),
("4", "Ich habe noch nie versehentlich etwas Falsches gegessen.", "I have never accidentally eaten something wrong.", "4", "6", "0"),
("4", "Ich bin noch nie an einem wichtigen Tag zu spät aufgewacht.", "I have never woken up late on an important day.", "5", "6", "0"),
("4", "Ich habe noch nie etwas absichtlich kaputt gemacht, um es nicht benutzen zu müssen.", "I have never deliberately broken something to avoid using it.", "4", "6", "0"),
("4", "Ich bin noch nie ohne Geld aus dem Haus gegangen.", "I have never left the house without money.", "4", "5", "0"),
("4", "Ich habe noch nie vergessen, meinen Wecker zu stellen.", "I have never forgotten to set my alarm clock.", "3", "4", "0"),
("4", "Ich bin noch nie in der Öffentlichkeit mit der Hose runter gerutscht.", "I have never had my pants fall down in public.", "6", "9", "0"),
("4", "Ich habe noch nie etwas aus dem Kühlschrank gegessen, das schon abgelaufen war.", "I have never eaten something from the fridge that was already expired.", "4", "6", "0"),
("4", "Ich bin noch nie aus Versehen in das falsche Auto gestiegen.", "I have never accidentally gotten into the wrong car.", "4", "7", "0"),
("4", "Ich habe noch nie etwas Wichtiges vergessen, das ich jemandem versprochen habe.", "I have never forgotten something important I promised someone.", "4", "6", "0"),
("4", "Ich bin noch nie versehentlich gegen eine Glastür gelaufen.", "I have never accidentally walked into a glass door.", "4", "7", "0"),
("4", "Ich habe noch nie jemanden aus Versehen angerufen.", "I have never accidentally called someone.", "2", "4", "0"),
("4", "Ich bin noch nie in der Öffentlichkeit ausgelaufen.", "I have never leaked in public.", "5", "8", "0"),
("4", "Ich habe noch nie einen peinlichen Anruf erhalten.", "I have never received an embarrassing call.", "2", "5", "0"),
("4", "Ich bin noch nie versehentlich mit einem offenen Reißverschluss herumgelaufen.", "I have never accidentally walked around with an open zipper.", "4", "7", "0"),
("4", "Ich habe noch nie jemanden aus Versehen beleidigt.", "I have never accidentally insulted someone.", "3", "6", "0"),
("4", "Ich bin noch nie betrunken aufgewacht und wusste nicht, wie ich nach Hause gekommen bin.", "I have never woken up drunk and not known how I got home.", "8", "8", "1"),
("4", "Ich habe noch nie in der Öffentlichkeit geschrien.", "I have never screamed in public.", "4", "5", "0"),
("4", "Ich bin noch nie betrunken im falschen Bett aufgewacht.", "I have never woken up drunk in the wrong bed.", "8", "9", "1"),
("4", "Ich habe noch nie betrunken etwas Peinliches getan, was ich am nächsten Tag bereut habe.", "I have never done something embarrassing while drunk that I regretted the next day.", "8", "9", "1"),
("4", "Ich bin noch nie betrunken eingeschlafen, bevor die Party vorbei war.", "I have never fallen asleep drunk before the party was over.", "7", "6", "1"),
("4", "Ich habe noch nie betrunken jemanden geküsst, den ich nicht hätte küssen sollen.", "I have never kissed someone I shouldn't have while drunk.", "9", "8", "1"),
("4", "Ich bin noch nie betrunken aufgewacht und konnte mich an nichts mehr erinnern.", "I have never woken up drunk and not remembered anything.", "9", "9", "1"),
("4", "Ich habe noch nie betrunken jemanden eine peinliche Nachricht geschickt.", "I have never sent someone an embarrassing message while drunk.", "8", "9", "1"),
("4", "Ich bin noch nie betrunken auf der Toilette eingeschlafen.", "I have never fallen asleep drunk on the toilet.", "8", "8", "1"),
("4", "Ich habe noch nie betrunken eine peinliche Geschichte erzählt.", "I have never told an embarrassing story while drunk.", "8", "8", "1"),
("4", "Ich bin noch nie betrunken gestolpert und hingefallen.", "I have never tripped and fallen while drunk.", "8", "7", "1"),
("4", "Ich habe noch nie betrunken versucht zu kochen und es völlig vermasselt.", "I have never tried to cook while drunk and completely messed it up.", "8", "8", "1"),
("4", "Ich bin noch nie betrunken mit der falschen Person nach Hause gegangen.", "I have never gone home with the wrong person while drunk.", "9", "9", "1"),
("4", "Ich habe noch nie betrunken etwas gekauft und es bereut.", "I have never bought something while drunk and regretted it.", "8", "7", "1"),
("4", "Ich bin noch nie betrunken aufgewacht und hatte einen Kater.", "I have never woken up drunk with a hangover.", "7", "6", "1"),
("4", "Ich habe noch nie betrunken jemanden angerufen und es bereut.", "I have never called someone while drunk and regretted it.", "8", "8", "1"),
("4", "Ich bin noch nie betrunken auf einer Party eingeschlafen.", "I have never fallen asleep drunk at a party.", "7", "7", "1"),
("4", "Ich habe noch nie betrunken etwas in einem Club verloren.", "I have never lost something in a club while drunk.", "7", "6", "1"),
("4", "Ich bin noch nie betrunken aufgewacht und wusste nicht, wo ich war.", "I have never woken up drunk and not known where I was.", "9", "9", "1"),
("4", "Ich habe noch nie betrunken versucht zu tanzen und es völlig vermasselt.", "I have never tried to dance while drunk and completely messed it up.", "7", "7", "1"),
("4", "Ich bin noch nie betrunken in die falsche Richtung gelaufen.", "I have never walked in the wrong direction while drunk.", "7", "6", "1"),
("4", "Ich habe noch nie betrunken eine Freundschaft ruiniert.", "I have never ruined a friendship while drunk.", "9", "9", "1"),
("4", "Ich bin noch nie betrunken in einem fremden Bett aufgewacht.", "I have never woken up drunk in a stranger's bed.", "9", "9", "1"),
("4", "Ich habe noch nie betrunken versucht zu schwimmen.", "I have never tried to swim while drunk.", "8", "7", "1"),
("4", "Ich bin noch nie betrunken auf der Straße eingeschlafen.", "I have never fallen asleep on the street while drunk.", "9", "9", "1");
