INSERT INTO game_klassiker_questions (fk_pool, content, content_english, drunk_level, exposure_level, bool_drink) VALUES
("9", "#1 gegen #2: Wer kann am längsten die Luft anhalten?", "#1 vs. #2: Who can hold their breath the longest?", "0", "2", "0"),
("9", "#1 gegen #2: Wer kann schneller ein Glas Wasser trinken?", "#1 vs. #2: Who can drink a glass of water faster?", "3", "2", "1"),
("9", "#1 gegen #2: Wer kann am längsten auf einem Bein stehen?", "#1 vs. #2: Who can stand on one leg the longest?", "0", "1", "0"),
("9", "#1 gegen #2: Wer kann lauter rülpsen?", "#1 vs. #2: Who can burp louder?", "5", "6", "1"),
("9", "#1 gegen #2: Wer kann schneller ein Lied rückwärts singen?", "#1 vs. #2: Who can sing a song backwards faster?", "0", "4", "0"),
("9", "#1 gegen #2: Wer kann die meisten Marshmallows in den Mund nehmen?", "#1 vs. #2: Who can fit the most marshmallows in their mouth?", "2", "5", "1"),
("9", "#1 gegen #2: Wer kann den besten Witz erzählen?", "#1 vs. #2: Who can tell the best joke?", "0", "3", "0"),
("9", "#1 gegen #2: Wer kann schneller das Alphabet aufsagen?", "#1 vs. #2: Who can recite the alphabet faster?", "0", "1", "0"),
("9", "#1 gegen #2: Wer kann länger ohne zu lachen ernst bleiben?", "#1 vs. #2: Who can keep a straight face longer without laughing?", "0", "2", "0"),
("9", "#1 gegen #2: Wer kann die meisten Kniebeugen machen?", "#1 vs. #2: Who can do the most squats?", "0", "3", "0"),
("9", "#1 gegen #2: Wer kann am längsten schweigen?", "#1 vs. #2: Who can stay silent the longest?", "0", "2", "0"),
("9", "#1 gegen #2: Wer kann am besten ein Tier nachmachen?", "#1 vs. #2: Who can imitate an animal the best?", "0", "4", "0"),
("9", "#1 gegen #2: Wer kann besser tanzen?", "#1 vs. #2: Who can dance better?", "0", "3", "0"),
("9", "#1 gegen #2: Wer kann schneller einen Zungenbrecher sagen?", "#1 vs. #2: Who can say a tongue twister faster?", "0", "2", "0"),
("9", "#1 gegen #2: Wer kann am längsten auf einem Stuhl balancieren?", "#1 vs. #2: Who can balance on a chair the longest?", "0", "4", "0"),
("9", "#1 gegen #2: Wer kann eine Geschichte überzeugender erzählen?", "#1 vs. #2: Who can tell a story more convincingly?", "0", "3", "0"),
("9", "#1 gegen #2: Wer kann den besten Zaubertrick vorführen?", "#1 vs. #2: Who can perform the best magic trick?", "0", "4", "0"),
("9", "#1 gegen #2: Wer kann schneller einen Schuh binden?", "#1 vs. #2: Who can tie a shoe faster?", "0", "1", "0"),
("9", "#1 gegen #2: Wer kann mehr Papierschiffe falten?", "#1 vs. #2: Who can fold more paper boats?", "0", "1", "0"),
("9", "#1 gegen #2: Wer kann am längsten auf einer Stelle hüpfen?", "#1 vs. #2: Who can hop on one spot the longest?", "0", "2", "0"),
("9", "#1 gegen #2: Wer kann am längsten eine Grimasse halten?", "#1 vs. #2: Who can hold a grimace the longest?", "0", "3", "0"),
("9", "#1 gegen #2: Wer kann am längsten summen?", "#1 vs. #2: Who can hum the longest?", "0", "1", "0"),
("9", "#1 gegen #2: Wer kann das Alphabet rückwärts aufsagen?", "#1 vs. #2: Who can recite the alphabet backwards?", "0", "2", "0"),
("9", "#1 gegen #2: Wer kann am besten pfeifen?", "#1 vs. #2: Who can whistle the best?", "0", "1", "0"),
("9", "#1 gegen #2: Wer kann schneller eine Banane essen?", "#1 vs. #2: Who can eat a banana faster?", "1", "2", "1"),
("9", "#1 gegen #2: Wer kann eine Münze weiter spucken?", "#1 vs. #2: Who can spit a coin further?", "0", "4", "0"),
("9", "#1 gegen #2: Wer kann besser zeichnen?", "#1 vs. #2: Who can draw better?", "0", "3", "0"),
("9", "#1 gegen #2: Wer kann schneller rückwärts laufen?", "#1 vs. #2: Who can run backwards faster?", "0", "2", "0"),
("9", "#1 gegen #2: Wer kann länger auf den Händen stehen?", "#1 vs. #2: Who can stand on their hands the longest?", "0", "4", "0"),
("9", "#1 gegen #2: Wer kann einen schwierigeren Zungenbrecher sagen?", "#1 vs. #2: Who can say a harder tongue twister?", "0", "2", "0"),
("9", "#1 gegen #2: Wer kann schneller 10 Dinge nennen, die man im Haushalt findet?", "#1 vs. #2: Who can name 10 household items faster?", "0", "1", "0"),
("9", "#1 gegen #2: Wer kann länger auf einem Bein hüpfen?", "#1 vs. #2: Who can hop on one leg the longest?", "0", "2", "0"),
("9", "#1 gegen #2: Wer kann ein Gedicht besser vortragen?", "#1 vs. #2: Who can recite a poem better?", "0", "3", "0"),
("9", "#1 gegen #2: Wer kann eine bessere Seifenblase pusten?", "#1 vs. #2: Who can blow a better soap bubble?", "0", "2", "0"),
("9", "#1 gegen #2: Wer kann den besseren Papierflieger basteln?", "#1 vs. #2: Who can make a better paper plane?", "0", "1", "0"),
("9", "#1 gegen #2: Wer kann länger tanzen, ohne Pause?", "#1 vs. #2: Who can dance longer without a break?", "0", "3", "0"),
("9", "#1 gegen #2: Wer kann mehr Witze in einer Minute erzählen?", "#1 vs. #2: Who can tell more jokes in a minute?", "0", "2", "0"),
("9", "#1 gegen #2: Wer kann schneller ein Lied erfinden?", "#1 vs. #2: Who can make up a song faster?", "0", "4", "0"),
("9", "#1 gegen #2: Wer kann besser Schattentiere mit den Händen machen?", "#1 vs. #2: Who can make better shadow animals with their hands?", "0", "3", "0"),
("9", "#1 gegen #2: Wer kann länger ein Bein hinter den Kopf legen?", "#1 vs. #2: Who can hold their leg behind their head longer?", "0", "5", "0"),
("9", "#1 gegen #2: Wer kann mehr Saltos machen?", "#1 vs. #2: Who can do more somersaults?", "0", "6", "0"),
("9", "#1 gegen #2: Wer kann schneller die Farbe ändern?", "#1 vs. #2: Who can change color faster?", "0", "1", "0"),
("9", "#1 gegen #2: Wer kann länger ein Ei auf dem Löffel balancieren?", "#1 vs. #2: Who can balance an egg on a spoon longer?", "0", "4", "0"),
("9", "#1 gegen #2: Wer kann besser einen Ballon aufblasen?", "#1 vs. #2: Who can blow up a balloon better?", "0", "1", "0"),
("9", "#1 gegen #2: Wer kann mehr Witze erzählen, ohne zu lachen?", "#1 vs. #2: Who can tell more jokes without laughing?", "0", "3", "0"),
("9", "#1 gegen #2: Wer kann schneller eine Flasche öffnen?", "#1 vs. #2: Who can open a bottle faster?", "2", "1", "1"),
("9", "#1 gegen #2: Wer kann länger ein Kissen balancieren?", "#1 vs. #2: Who can balance a pillow longer?", "0", "2", "0"),
("9", "#1 gegen #2: Wer kann eine bessere Grimasse ziehen?", "#1 vs. #2: Who can make a better funny face?", "0", "3", "0"),
("9", "#1 gegen #2: Wer kann schneller das 1x1 aufsagen?", "#1 vs. #2: Who can recite the times tables faster?", "0", "1", "0"),
("9", "#1 gegen #2: Wer kann mehr Punkte in Darts erreichen?", "#1 vs. #2: Who can score more points in darts?", "0", "2", "0"),
("9", "#1 gegen #2: Wer kann mehr Liegestütze in einer Minute machen?", "#1 vs. #2: Who can do more push-ups in a minute?", "0", "3", "0"),
("9", "#1 gegen #2: Wer kann schneller einen Apfel schälen?", "#1 vs. #2: Who can peel an apple faster?", "0", "1", "0"),
("9", "#1 gegen #2: Wer kann besser ein Gedicht schreiben?", "#1 vs. #2: Who can write a better poem?", "0", "3", "0"),
("9", "#1 gegen #2: Wer kann mehr Papierflieger basteln, die fliegen?", "#1 vs. #2: Who can make more paper planes that fly?", "0", "1", "0"),
("9", "#1 gegen #2: Wer kann besser eine Sprache imitieren, die sie nicht sprechen?", "#1 vs. #2: Who can better imitate a language they don't speak?", "0", "4", "0"),
("9", "#1 gegen #2: Wer kann länger in einem Buch lesen, ohne zu lachen?", "#1 vs. #2: Who can read a book longer without laughing?", "0", "2", "0"),
("9", "#1 gegen #2: Wer kann schneller einen Ball fangen?", "#1 vs. #2: Who can catch a ball faster?", "0", "1", "0"),
("9", "#1 gegen #2: Wer kann besser singen?", "#1 vs. #2: Who can sing better?", "0", "3", "0"),
("9", "#1 gegen #2: Wer kann mehr Punkte im Basketball erreichen?", "#1 vs. #2: Who can score more points in basketball?", "0", "2", "0"),
("9", "#1 gegen #2: Wer kann schneller ein Gedicht auswendig lernen?", "#1 vs. #2: Who can memorize a poem faster?", "0", "3", "0"),
("9", "#1 gegen #2: Wer kann besser einen Schauspielmonolog vortragen?", "#1 vs. #2: Who can perform an acting monologue better?", "0", "4", "0"),
("9", "#1 gegen #2: Wer kann schneller einen Zopf flechten?", "#1 vs. #2: Who can braid hair faster?", "0", "1", "0"),
("9", "#1 gegen #2: Wer kann länger die Augen offen halten, ohne zu blinzeln?", "#1 vs. #2: Who can keep their eyes open longer without blinking?", "0", "2", "0"),
("9", "#1 gegen #2: Wer kann schneller eine SMS tippen?", "#1 vs. #2: Who can type a text message faster?", "0", "1", "0"),
("9", "#1 gegen #2: Wer kann besser pantomimisch darstellen?", "#1 vs. #2: Who can perform better pantomime?", "0", "4", "0"),
("9", "#1 gegen #2: Wer kann schneller einen Origami-Kranich falten?", "#1 vs. #2: Who can fold an origami crane faster?", "0", "1", "0"),
("9", "#1 gegen #2: Wer kann länger auf einem Seil balancieren?", "#1 vs. #2: Who can balance on a rope longer?", "0", "5", "0"),
("9", "#1 gegen #2: Wer kann besser einen Trick mit einem Stift vorführen?", "#1 vs. #2: Who can perform a better trick with a pen?", "0", "3", "0"),
("9", "#1 gegen #2: Wer kann schneller einen Tisch decken?", "#1 vs. #2: Who can set a table faster?", "0", "1", "0"),
("9", "#1 gegen #2: Wer kann länger ohne Pausen sprechen?", "#1 vs. #2: Who can speak longer without pausing?", "0", "3", "0"),
("9", "#1 gegen #2: Wer kann schneller ein Hemd bügeln?", "#1 vs. #2: Who can iron a shirt faster?", "0", "1", "0"),
("9", "#1 gegen #2: Wer kann mehr Purzelbäume schlagen?", "#1 vs. #2: Who can do more cartwheels?", "0", "6", "0"),
("9", "#1 gegen #2: Wer kann besser einen Ballonmodellierhund formen?", "#1 vs. #2: Who can better shape a balloon dog?", "0", "4", "0"),
("9", "#1 gegen #2: Wer kann mehr Fakten über Tiere nennen?", "#1 vs. #2: Who can name more animal facts?", "0", "2", "0"),
("9", "#1 gegen #2: Wer kann schneller eine Melodie pfeifen?", "#1 vs. #2: Who can whistle a tune faster?", "0", "1", "0"),
("9", "#1 gegen #2: Wer kann mehr Jonglierbälle in der Luft halten?", "#1 vs. #2: Who can keep more juggling balls in the air?", "0", "5", "0"),
("9", "#1 gegen #2: Wer kann schneller eine Nadel einfädeln?", "#1 vs. #2: Who can thread a needle faster?", "0", "1", "0"),
("9", "#1 gegen #2: Wer kann besser einen Film beschreiben, ohne den Titel zu nennen?", "#1 vs. #2: Who can better describe a movie without naming the title?", "0", "4", "0"),
("9", "#1 gegen #2: Wer kann schneller ein Fahrrad reparieren?", "#1 vs. #2: Who can fix a bike faster?", "0", "2", "0"),
("9", "#1 gegen #2: Wer kann länger auf Zehenspitzen stehen?", "#1 vs. #2: Who can stand on tiptoes longer?", "0", "3", "0"),
("9", "#1 gegen #2: Wer kann schneller einen Text in Morsecode übersetzen?", "#1 vs. #2: Who can translate a text into Morse code faster?", "0", "2", "0"),
("9", "#1 gegen #2: Wer kann besser eine Werbeanzeige erfinden?", "#1 vs. #2: Who can come up with a better advertisement?", "0", "4", "0"),
("9", "#1 gegen #2: Wer kann schneller einen Ballon aufblasen?", "#1 vs. #2: Who can blow up a balloon faster?", "0", "1", "0"),
("9", "#1 gegen #2: Wer kann länger mit einem Buch auf dem Kopf gehen?", "#1 vs. #2: Who can walk longer with a book on their head?", "0", "3", "0"),
("9", "#1 gegen #2: Wer kann schneller ein Puzzle lösen?", "#1 vs. #2: Who can solve a puzzle faster?", "0", "2", "0"),
("9", "#1 gegen #2: Wer kann besser einen Pantomime-Akt vorführen?", "#1 vs. #2: Who can perform a better pantomime act?", "0", "4", "0"),
("9", "#1 gegen #2: Wer kann mehr Sprichwörter nennen?", "#1 vs. #2: Who can name more proverbs?", "0", "2", "0"),
("9", "#1 gegen #2: Wer kann schneller eine Melodie auf einem Instrument spielen?", "#1 vs. #2: Who can play a tune faster on an instrument?", "0", "1", "0"),
("9", "#1 gegen #2: Wer kann besser eine Geschichte erfinden?", "#1 vs. #2: Who can come up with a better story?", "0", "4", "0"),
("9", "#1 gegen #2: Wer kann schneller ein Haus aus Karten bauen?", "#1 vs. #2: Who can build a house of cards faster?", "0", "3", "0"),
("9", "#1 gegen #2: Wer kann länger einen Stift auf dem Finger balancieren?", "#1 vs. #2: Who can balance a pen on their finger longer?", "0", "2", "0"),
("9", "#1 gegen #2: Wer kann schneller eine schwierige Matheaufgabe lösen?", "#1 vs. #2: Who can solve a difficult math problem faster?", "0", "1", "0");
