INSERT INTO game_klassiker_questions (fk_pool, content, content_english, drunk_level, exposure_level, bool_drink) VALUES
("3", "Trinke einen Shot ohne deine Hände zu benutzen.", "Drink a shot without using your hands.", "10", "5", "1"),
("3", "Erzähle einen Witz. Wenn niemand lacht, trinke einen Shot.", "Tell a joke. If no one laughs, drink a shot.", "5", "3", "1"),
("3", "Tanzt 30 Sekunden lang ohne Musik.", "Dance for 30 seconds without music.", "0", "4", "0"),
("3", "Mache 10 Liegestütze.", "Do 10 push-ups.", "0", "3", "0"),
("3", "Zeichne ein Bild mit verbundenen Augen und lasse die Gruppe raten, was es ist.", "Draw a picture with your eyes closed and let the group guess what it is.", "0", "6", "0"),
("3", "Versuche, eine Minute lang auf einem Bein zu stehen, ohne das Gleichgewicht zu verlieren.", "Try to stand on one leg for a minute without losing balance.", "0", "5", "0"),
("3", "Erzähle der Gruppe von deinem peinlichsten Moment.", "Tell the group about your most embarrassing moment.", "0", "8", "0"),
("3", "Tausche ein Kleidungsstück mit der Person rechts von dir.", "Swap one piece of clothing with the person to your right.", "2", "6", "0"),
("3", "Trinke drei Schlucke von deinem Getränk.", "Take three sips of your drink.", "7", "2", "1"),
("3", "Imitiere jemanden aus der Gruppe und lasse die anderen raten, wer es ist.", "Imitate someone from the group and let the others guess who it is.", "0", "5", "0"),
("3", "Lasse dir von jemandem aus der Gruppe ein Getränk mischen und trinke es.", "Have someone from the group mix a drink for you and drink it.", "8", "4", "1"),
("3", "Sing dein Lieblingslied ohne Musik.", "Sing your favorite song without music.", "0", "7", "0"),
("3", "Lass dir von jemandem aus der Gruppe eine verrückte Frisur machen.", "Have someone from the group give you a crazy hairstyle.", "1", "7", "0"),
("3", "Erzähle der Gruppe einen lustigen Kindheitserinnerung.", "Tell the group a funny childhood memory.", "0", "4", "0"),
("3", "Trinke einen Shot in weniger als 10 Sekunden.", "Drink a shot in less than 10 seconds.", "10", "3", "1"),
("3", "Erzähle der Gruppe etwas, was du noch nie jemandem erzählt hast.", "Tell the group something you've never told anyone.", "0", "9", "0"),
("3", "Lass dir von jemandem aus der Gruppe ein Tattoo zeichnen (mit einem Stift).", "Have someone from the group draw a tattoo on you (with a pen).", "0", "6", "0"),
("3", "Versuche, jemanden in der Gruppe zum Lachen zu bringen. Wenn du es nicht schaffst, trinke einen Shot.", "Try to make someone in the group laugh. If you fail, drink a shot.", "5", "5", "1"),
("3", "Tanze eine Minute lang den Macarena.", "Dance the Macarena for a minute.", "0", "4", "0"),
("3", "Trinke drei Schlucke eines Getränks, das jemand anders gewählt hat.", "Take three sips of a drink chosen by someone else.", "7", "4", "1"),
("3", "Erzähle der Gruppe deinen ersten Kuss.", "Tell the group about your first kiss.", "0", "8", "0"),
("3", "Lass dich von der Gruppe wie einen Superhelden einkleiden.", "Let the group dress you up as a superhero.", "1", "6", "0"),
("3", "Trinke einen Shot und mache danach 5 Kniebeugen.", "Drink a shot and then do 5 squats.", "10", "3", "1"),
("3", "Versuche, ein Glas Wasser zu trinken, während du dich nach hinten lehnst.", "Try to drink a glass of water while leaning back.", "3", "4", "0"),
("3", "Mach eine Grimasse und halte sie 30 Sekunden lang.", "Make a funny face and hold it for 30 seconds.", "0", "5", "0"),
("3", "Trinke ein Glas Wasser so schnell wie möglich.", "Drink a glass of water as quickly as possible.", "2", "3", "0"),
("3", "Erzähle der Gruppe, was du letzte Nacht geträumt hast.", "Tell the group about your dream last night.", "0", "4", "0"),
("3", "Spiele Luftgitarre zu einem Lied deiner Wahl.", "Play air guitar to a song of your choice.", "0", "4", "0"),
("3", "Lass dir von der Gruppe ein neues Outfit aussuchen und zieh es an.", "Let the group choose a new outfit for you and wear it.", "2", "7", "0"),
("3", "Trinke einen Shot durch einen Strohhalm.", "Drink a shot through a straw.", "10", "2", "1"),
("3", "Erzähle der Gruppe deine peinlichste Geschichte von der Schule.", "Tell the group your most embarrassing school story.", "0", "8", "0"),
("3", "Mach den Wurm für 30 Sekunden.", "Do the worm dance for 30 seconds.", "0", "5", "0"),
("3", "Trinke einen Shot und versuche dann, auf einem Bein zu balancieren.", "Drink a shot and then try to balance on one leg.", "10", "4", "1"),
("3", "Lass dir von jemandem aus der Gruppe die Augen verbinden und dann versuche, ein Getränk einzuschenken.", "Let someone from the group blindfold you and then try to pour a drink.", "3", "5", "0"),
("3", "Erzähle der Gruppe von deinem verrücktesten Traum.", "Tell the group about your craziest dream.", "0", "4", "0"),
("3", "Trinke einen Shot und erzähle der Gruppe einen Witz.", "Drink a shot and tell the group a joke.", "10", "3", "1"),
("3", "Lass dir von der Gruppe ein lustiges Outfit zusammenstellen und zieh es an.", "Let the group put together a funny outfit for you and wear it.", "1", "6", "0"),
("3", "Trinke drei Schlucke aus dem Getränk der Person links von dir.", "Take three sips from the drink of the person to your left.", "8", "4", "1"),
("3", "Mach eine Rolle vorwärts.", "Do a forward roll.", "0", "4", "0"),
("3", "Erzähle der Gruppe einen lustigen Witz.", "Tell the group a funny joke.", "0", "3", "0"),
("3", "Trinke einen Shot und versuche dann, das Alphabet rückwärts aufzusagen.", "Drink a shot and then try to say the alphabet backwards.", "10", "5", "1"),
("3", "Lass dir von jemandem aus der Gruppe eine neue Frisur machen.", "Let someone from the group give you a new hairstyle.", "1", "7", "0"),
("3", "Erzähle der Gruppe deine erste Erinnerung.", "Tell the group your first memory.", "0", "4", "0"),
("3", "Trinke einen Shot und dann erzähle der Gruppe eine Lüge. Lass die Gruppe raten, ob es wahr oder falsch ist.", "Drink a shot and then tell the group a lie. Let the group guess if it's true or false.", "10", "4", "1"),
("3", "Zeige der Gruppe dein bestes Tanzmove.", "Show the group your best dance move.", "0", "5", "0"),
("3", "Lass dir von jemandem aus der Gruppe einen Schnurrbart malen.", "Let someone from the group draw a mustache on you.", "0", "6", "0"),
("3", "Trinke drei Schlucke und mache danach 10 Kniebeugen.", "Take three sips and then do 10 squats.", "7", "3", "1"),
("3", "Erzähle der Gruppe, was du an der Person rechts von dir am meisten magst.", "Tell the group what you like most about the person to your right.", "0", "4", "0"),
("3", "Imitiere einen bekannten Schauspieler oder eine bekannte Schauspielerin und lass die Gruppe raten, wer es ist.", "Imitate a famous actor or actress and let the group guess who it is.", "0", "5", "0"),
("3", "Trinke einen Shot und erzähle der Gruppe eine lustige Geschichte aus deiner Kindheit.", "Drink a shot and tell the group a funny story from your childhood.", "10", "4", "1"),
("3", "Mache einen Handstand gegen die Wand für 10 Sekunden.", "Do a handstand against the wall for 10 seconds.", "0", "5", "0"),
("3", "Erzähle der Gruppe deinen peinlichsten Moment bei der Arbeit.", "Tell the group your most embarrassing moment at work.", "0", "8", "0"),
("3", "Lass dir von der Gruppe einen neuen Spitznamen geben.", "Let the group give you a new nickname.", "0", "4", "0"),
("3", "Trinke einen Shot und erzähle der Gruppe ein Geheimnis.", "Drink a shot and tell the group a secret.", "10", "5", "1"),
("3", "Mach eine Tiergeräusch und lass die Gruppe raten, welches Tier es ist.", "Make an animal sound and let the group guess what animal it is.", "0", "5", "0"),
("3", "Trinke drei Schlucke deines Getränks, während du singst.", "Take three sips of your drink while singing.", "7", "3", "1"),
("3", "Erzähle der Gruppe, was du am liebsten an deinem besten Freund oder deiner besten Freundin magst.", "Tell the group what you like most about your best friend.", "0", "4", "0"),
("3", "Lass dir von der Gruppe eine neue Frisur machen und behalte sie für den Rest des Spiels.", "Let the group give you a new hairstyle and keep it for the rest of the game.", "1", "7", "0"),
("3", "Trinke einen Shot und erzähle der Gruppe deine peinlichste Liebesgeschichte.", "Drink a shot and tell the group your most embarrassing love story.", "10", "6", "1"),
("3", "Mache einen Kopfstand für 10 Sekunden.", "Do a headstand for 10 seconds.", "0", "5", "0"),
("3", "Erzähle der Gruppe deinen lustigsten Urlaubserlebnis.", "Tell the group about your funniest holiday experience.", "0", "4", "0"),
("3", "Trinke einen Shot und mache danach 5 Liegestütze.", "Drink a shot and then do 5 push-ups.", "10", "3", "1"),
("3", "Lass dir von der Gruppe ein neues Parfüm aussuchen und trage es auf.", "Let the group choose a new perfume for you and apply it.", "0", "4", "0"),
("3", "Trinke drei Schlucke und erzähle der Gruppe einen peinlichen Moment aus deiner Kindheit.", "Take three sips and tell the group an embarrassing moment from your childhood.", "7", "6", "1"),
("3", "Erzähle der Gruppe dein Lieblingswitz.", "Tell the group your favorite joke.", "0", "3", "0"),
("3", "Trinke einen Shot und imitiere danach einen berühmten Sänger oder eine berühmte Sängerin.", "Drink a shot and then imitate a famous singer.", "10", "5", "1"),
("3", "Lass dir von der Gruppe einen lustigen Spitznamen geben und benutze ihn für den Rest des Spiels.", "Let the group give you a funny nickname and use it for the rest of the game.", "0", "4", "0"),
("3", "Trinke drei Schlucke eines Getränks, das die Gruppe ausgewählt hat.", "Take three sips of a drink chosen by the group.", "7", "4", "1"),
("3", "Erzähle der Gruppe eine lustige Geschichte über dich und deine Familie.", "Tell the group a funny story about you and your family.", "0", "4", "0"),
("3", "Trinke einen Shot und mache danach eine Minute lang Hampelmänner.", "Drink a shot and then do jumping jacks for a minute.", "10", "3", "1"),
("3", "Lass dir von der Gruppe ein neues Accessoire geben und trage es für den Rest des Spiels.", "Let the group give you a new accessory and wear it for the rest of the game.", "0", "4", "0"),
("3", "Erzähle der Gruppe dein peinlichstes Erlebnis beim ersten Date.", "Tell the group about your most embarrassing first date experience.", "0", "8", "0"),
("3", "Trinke einen Shot und erzähle der Gruppe deinen lustigsten Witz.", "Drink a shot and tell the group your funniest joke.", "10", "3", "1"),
("3", "Mache 20 Sekunden lang den Gangnam Style Tanz.", "Do the Gangnam Style dance for 20 seconds.", "0", "5", "0"),
("3", "Erzähle der Gruppe, was du am meisten an der Person links von dir magst.", "Tell the group what you like most about the person to your left.", "0", "4", "0"),
("3", "Trinke einen Shot und singe danach dein Lieblingslied.", "Drink a shot and then sing your favorite song.", "10", "5", "1"),
("3", "Erzähle der Gruppe dein lustigstes Erlebnis auf einer Party.", "Tell the group your funniest party experience.", "0", "4", "0"),
("3", "Trinke drei Schlucke und imitiere danach ein Tier.", "Take three sips and then imitate an animal.", "7", "5", "1"),
("3", "Lass dir von jemandem aus der Gruppe ein Make-up machen.", "Let someone from the group do your makeup.", "0", "7", "0"),
("3", "Trinke einen Shot und erzähle der Gruppe von deinem peinlichsten Moment in der Schule.", "Drink a shot and tell the group about your most embarrassing school moment.", "10", "6", "1"),
("3", "Erzähle der Gruppe dein Lieblingswitz aus der Kindheit.", "Tell the group your favorite childhood joke.", "0", "3", "0"),
("3", "Trinke drei Schlucke und erzähle danach eine Lüge. Lass die Gruppe raten, ob es wahr oder falsch ist.", "Take three sips and then tell a lie. Let the group guess if it's true or false.", "7", "4", "1"),
("3", "Lass dir von der Gruppe einen lustigen Namen geben und benutze ihn für den Rest des Spiels.", "Let the group give you a funny name and use it for the rest of the game.", "0", "4", "0"),
("3", "Trinke einen Shot und mache danach 5 Sit-ups.", "Drink a shot and then do 5 sit-ups.", "10", "3", "1"),
("3", "Erzähle der Gruppe dein lustigstes Erlebnis mit einem Haustier.", "Tell the group your funniest pet experience.", "0", "4", "0"),
("3", "Mache einen Kopfstand für 5 Sekunden.", "Do a headstand for 5 seconds.", "0", "5", "0"),
("3", "Trinke drei Schlucke und erzähle der Gruppe etwas, was du noch nie jemandem erzählt hast.", "Take three sips and tell the group something you've never told anyone.", "7", "9", "1");
