INSERT INTO game_klassiker_questions (fk_pool, content, content_english, drunk_level, exposure_level, bool_drink) VALUES
("5", "Biermarken", "Beer brands", "0", "2", "0"),
("5", "Obstsorten", "Types of fruit", "0", "1", "0"),
("5", "Orte, an denen # schon war", "Places # has been to", "0", "4", "0"),
("5", "Essen, das # noch nie gegessen hat", "Foods # has never eaten", "0", "5", "0"),
("5", "Automarken", "Car brands", "0", "2", "0"),
("5", "Hunderassen", "Dog breeds", "0", "1", "0"),
("5", "Filme, die # mag", "Movies # likes", "0", "3", "0"),
("5", "Bücher, die # gelesen hat", "Books # has read", "0", "3", "0"),
("5", "Sportarten", "Types of sports", "0", "2", "0"),
("5", "Länder in Europa", "Countries in Europe", "0", "1", "0"),
("5", "Getränke, die # gerne trinkt", "Drinks # likes", "0", "3", "0"),
("5", "Farbe von Kleidungsstücken, die # besitzt", "Colors of clothes # owns", "0", "2", "0"),
("5", "Berühmte Persönlichkeiten", "Famous personalities", "0", "2", "0"),
("5", "Züge von Brettspielen", "Board game moves", "0", "1", "0"),
("5", "Computerprogramme", "Computer programs", "0", "1", "0"),
("5", "Musikinstrumente", "Musical instruments", "0", "1", "0"),
("5", "Marken von Smartphones", "Smartphone brands", "0", "2", "0"),
("5", "Berufe, die # interessant findet", "Jobs # finds interesting", "0", "3", "0"),
("5", "Superhelden", "Superheroes", "0", "1", "0"),
("5", "Getränke, die # nie trinken würde", "Drinks # would never drink", "5", "5", "1"),
("5", "Spielzeuge aus der Kindheit", "Toys from childhood", "0", "2", "0"),
("5", "Arten von Ferien", "Types of holidays", "0", "2", "0"),
("5", "Eiscreme-Geschmacksrichtungen", "Ice cream flavors", "0", "1", "0"),
("5", "Automodelle", "Car models", "0", "2", "0"),
("5", "Marken von Haushaltsgeräten", "Brands of household appliances", "0", "1", "0"),
("5", "Fahrzeuge, die # fahren kann", "Vehicles # can drive", "0", "3", "0"),
("5", "Arten von Blumen", "Types of flowers", "0", "1", "0"),
("5", "Tiere im Zoo", "Animals in the zoo", "0", "1", "0"),
("5", "Orte, an die # reisen möchte", "Places # wants to travel to", "0", "4", "0"),
("5", "Lieblingsessen von #", "Favorite foods of #", "0", "3", "0"),
("5", "Pizzabeläge", "Pizza toppings", "0", "2", "0"),
("5", "Gerichte, die # gut kochen kann", "Dishes # can cook well", "0", "3", "0"),
("5", "Filme, die # nicht mag", "Movies # doesn't like", "0", "5", "0"),
("5", "Musikgenres", "Music genres", "0", "1", "0"),
("5", "Ferienorte, an denen # war", "Holiday destinations # has been to", "0", "3", "0"),
("5", "Getränke, die man auf Partys trinkt", "Drinks people have at parties", "5", "3", "1"),
("5", "Parfummarken", "Perfume brands", "0", "2", "0"),
("5", "Dinge, die # in einem Hotelzimmer mag", "Things # likes in a hotel room", "0", "2", "0"),
("5", "Tierarten, die # mag", "Animal species # likes", "0", "2", "0"),
("5", "Lieblingsfilme von #", "Favorite movies of #", "0", "3", "0"),
("5", "Sportarten, die # schon mal ausprobiert hat", "Sports # has tried", "0", "3", "0"),
("5", "Dinge, die # in der Schule gelernt hat", "Things # learned in school", "0", "1", "0"),
("5", "Eissorten, die # nicht mag", "Ice cream flavors # doesn't like", "0", "5", "0"),
("5", "Hobbies von #", "Hobbies of #", "0", "3", "0"),
("5", "Städte, in denen # leben möchte", "Cities # wants to live in", "0", "4", "0"),
("5", "Cocktails, die # gerne trinkt", "Cocktails # likes to drink", "7", "3", "1"),
("5", "Schulfächer, die # mochte", "School subjects # liked", "0", "3", "0"),
("5", "Dinge, die # gerne am Wochenende macht", "Things # likes to do on weekends", "0", "3", "0"),
("5", "Lieblingsrestaurants von #", "Favorite restaurants of #", "0", "2", "0"),
("5", "Berge, die # besteigen möchte", "Mountains # wants to climb", "0", "4", "0"),
("5", "Sportteams, die # unterstützt", "Sports teams # supports", "0", "2", "0"),
("5", "Computerspiele, die # gerne spielt", "Computer games # likes to play", "0", "2", "0"),
("5", "Lieblingsfarben von #", "Favorite colors of #", "0", "2", "0"),
("5", "TV-Serien, die # gerne schaut", "TV shows # likes to watch", "0", "3", "0"),
("5", "Schuhe, die # besitzt", "Shoes # owns", "0", "2", "0"),
("5", "Brettspiele, die # gerne spielt", "Board games # likes to play", "0", "2", "0"),
("5", "Länder, die # besuchen möchte", "Countries # wants to visit", "0", "4", "0"),
("5", "Essen, das # nie wieder essen möchte", "Food # never wants to eat again", "0", "5", "0"),
("5", "Gegenstände, die # jeden Tag benutzt", "Items # uses every day", "0", "2", "0"),
("5", "Orte, an denen # sich entspannen kann", "Places where # can relax", "0", "3", "0"),
("5", "Getränke, die man im Sommer trinkt", "Drinks people have in summer", "5", "2", "1"),
("5", "Pflanzen, die # im Garten hat", "Plants # has in the garden", "0", "2", "0"),
("5", "Lieblingssportarten von #", "Favorite sports of #", "0", "3", "0"),
("5", "Berufe, die # nie machen würde", "Jobs # would never do", "0", "5", "0"),
("5", "Dinge, die # im Urlaub macht", "Things # does on vacation", "0", "3", "0"),
("5", "Filme, die # mehr als einmal gesehen hat", "Movies # has watched more than once", "0", "3", "0"),
("5", "Musikbands, die # gerne hört", "Music bands # likes to listen to", "0", "2", "0"),
("5", "Hobbys, die # nie ausprobieren würde", "Hobbies # would never try", "0", "5", "0"),
("5", "Dinge, die # gerne sammelt", "Things # likes to collect", "0", "2", "0"),
("5", "Restaurants, die # gerne besucht", "Restaurants # likes to visit", "0", "2", "0"),
("5", "Getränke, die man im Winter trinkt", "Drinks people have in winter", "5", "2", "1"),
("5", "Süßigkeiten, die # gerne isst", "Sweets # likes to eat", "0", "2", "0"),
("5", "Sportarten, die # nie ausprobieren würde", "Sports # would never try", "0", "5", "0"),
("5", "Computerspiele, die # nie spielen würde", "Computer games # would never play", "0", "5", "0"),
("5", "Filme, die # nie sehen würde", "Movies # would never watch", "0", "5", "0"),
("5", "Länder, in denen # schon mal war", "Countries # has been to", "0", "3", "0"),
("5", "Schulfreunde von #", "School friends of #", "0", "4", "0"),
("5", "Getränke, die # nicht mag", "Drinks # doesn't like", "5", "5", "1"),
("5", "Tiere, die # gerne hätte", "Animals # would like to have", "0", "3", "0"),
("5", "Dinge, die # in der Küche hat", "Things # has in the kitchen", "0", "1", "0"),
("5", "Freizeitaktivitäten von #", "Leisure activities of #", "0", "3", "0"),
("5", "Getränke, die man im Club bestellt", "Drinks people order in a club", "7", "3", "1"),
("5", "Dinge, die # in der Schule gelernt hat", "Things # learned in school", "0", "1", "0"),
("5", "Künstler, die # mag", "Artists # likes", "0", "2", "0"),
("5", "Lieblingsorte von #", "Favorite places of #", "0", "3", "0"),
("5", "Sportstadien, die # besucht hat", "Sports stadiums # has visited", "0", "3", "0"),
("5", "Museen, die # besucht hat", "Museums # has visited", "0", "3", "0"),
("5", "Gerichte, die # gerne isst", "Dishes # likes to eat", "0", "3", "0"),
("5", "Orte, an denen # gerne Zeit verbringt", "Places # likes to spend time at", "0", "3", "0"),
("5", "Musikalben, die # gerne hört", "Music albums # likes to listen to", "0", "2", "0"),
("5", "Getränke, die # zum Frühstück trinkt", "Drinks # has for breakfast", "0", "2", "0"),
("5", "Dinge, die # am Morgen macht", "Things # does in the morning", "0", "2", "0"),
("5", "Essen, das # zum Mittag isst", "Foods # eats for lunch", "0", "2", "0"),
("5", "Arten von Sandwiches, die # mag", "Types of sandwiches # likes", "0", "2", "0"),
("5", "Parks, die # besucht hat", "Parks # has visited", "0", "3", "0");
