INSERT INTO game_klassiker_questions (fk_pool, content, content_english, drunk_level, exposure_level, bool_drink) VALUES
("10", "Wer kann am längsten auf einem Bein stehen?", "Who can stand on one leg the longest?", "0", "2", "0"),
("10", "Wer kann die meisten Liegestütze machen?", "Who can do the most push-ups?", "0", "3", "0"),
("10", "Wer kann am schnellsten das Alphabet rückwärts aufsagen?", "Who can recite the alphabet backwards the fastest?", "0", "4", "0"),
("10", "Wer kann am längsten ohne zu blinzeln starren?", "Who can stare the longest without blinking?", "0", "2", "0"),
("10", "Wer kann am lautesten singen?", "Who can sing the loudest?", "0", "4", "0"),
("10", "Wer kann am besten einen Zungenbrecher aufsagen?", "Who can say a tongue-twister the best?", "0", "3", "0"),
("10", "Wer kann am längsten einen Ballon in der Luft halten?", "Who can keep a balloon in the air the longest?", "0", "2", "0"),
("10", "Wer kann die meisten Sterne innerhalb von 10 Sekunden zählen?", "Who can count the most stars in 10 seconds?", "0", "1", "0"),
("10", "Wer kann am besten eine berühmte Persönlichkeit nachmachen?", "Who can impersonate a celebrity the best?", "0", "5", "0"),
("10", "Wer kann am längsten „lalalala“ sagen ohne Luft zu holen?", "Who can say 'lalalala' the longest without taking a breath?", "0", "3", "0"),
("10", "Wer kann den lustigsten Tanz vorführen?", "Who can perform the funniest dance?", "0", "5", "0"),
("10", "Wer kann am schnellsten das ABC singen?", "Who can sing the alphabet the fastest?", "0", "2", "0"),
("10", "Wer kann am längsten auf einer unsichtbaren Linie balancieren?", "Who can balance on an invisible line the longest?", "0", "3", "0"),
("10", "Wer kann die meisten Namen von Prominenten in einer Minute nennen?", "Who can name the most celebrities in one minute?", "0", "3", "0"),
("10", "Wer kann am längsten einen imaginären Hula-Hoop-Reifen drehen?", "Who can spin an imaginary hula hoop the longest?", "0", "4", "0"),
("10", "Wer kann die meisten Wörter in einer Minute reimen?", "Who can rhyme the most words in one minute?", "0", "3", "0"),
("10", "Wer kann am besten eine Tierstimme nachmachen?", "Who can imitate an animal sound the best?", "0", "5", "0"),
("10", "Wer kann am schnellsten das Wort „Schnell“ zehnmal hintereinander sagen?", "Who can say the word 'Fast' ten times in a row the fastest?", "0", "2", "0"),
("10", "Wer kann die meisten Luftsprünge in 30 Sekunden machen?", "Who can do the most jumps in 30 seconds?", "0", "3", "0"),
("10", "Wer kann am besten wie ein Roboter tanzen?", "Who can dance like a robot the best?", "0", "4", "0"),
("10", "Wer kann am längsten einen Songtitel summen?", "Who can hum a song title the longest?", "0", "3", "0"),
("10", "Wer kann am besten eine Melodie pfeifen?", "Who can whistle a melody the best?", "0", "3", "0"),
("10", "Wer kann den höchsten Turm aus Bechern bauen?", "Who can build the highest tower of cups?", "0", "2", "0"),
("10", "Wer kann die meisten Korken in eine Flasche werfen?", "Who can throw the most corks into a bottle?", "0", "2", "0"),
("10", "Wer kann am schnellsten die Worte „Blaukraut bleibt Blaukraut“ sagen?", "Who can say the words 'Blaukraut bleibt Blaukraut' the fastest?", "0", "3", "0"),
("10", "Wer kann am längsten auf einem Bein hüpfen?", "Who can hop on one leg the longest?", "0", "3", "0"),
("10", "Wer kann die meisten Farben in einer Minute aufzählen?", "Who can name the most colors in one minute?", "0", "1", "0"),
("10", "Wer kann am längsten eine Grimasse halten?", "Who can hold a funny face the longest?", "0", "4", "0"),
("10", "Wer kann am schnellsten einen Fingerabdruck erkennen?", "Who can identify a fingerprint the fastest?", "0", "1", "0"),
("10", "Wer kann am besten eine Geschichte erzählen?", "Who can tell the best story?", "0", "4", "0"),
("10", "Wer kann am meisten lachen, ohne Geräusche zu machen?", "Who can laugh the most without making a sound?", "0", "3", "0"),
("10", "Wer kann am besten jonglieren (mit imaginären Bällen)?", "Who can juggle (with imaginary balls) the best?", "0", "4", "0"),
("10", "Wer kann die meisten Wörter mit 'A' am Anfang in einer Minute nennen?", "Who can name the most words starting with 'A' in one minute?", "0", "2", "0"),
("10", "Wer kann am schnellsten eine Flasche Wasser trinken?", "Who can drink a bottle of water the fastest?", "5", "2", "1"),
("10", "Wer kann den längsten Schluck Wasser ohne abzusetzen trinken?", "Who can take the longest sip of water without stopping?", "5", "3", "1"),
("10", "Wer kann die meisten Namen von Automarken in einer Minute nennen?", "Who can name the most car brands in one minute?", "0", "1", "0"),
("10", "Wer kann am längsten eine Kerze ausblasen?", "Who can blow out a candle the longest?", "0", "3", "0"),
("10", "Wer kann am besten eine berühmte Filmszene nachspielen?", "Who can reenact a famous movie scene the best?", "0", "5", "0"),
("10", "Wer kann die meisten Länder in einer Minute aufzählen?", "Who can name the most countries in one minute?", "0", "1", "0"),
("10", "Wer kann am schnellsten das Wort „Katzenklappe“ zehnmal hintereinander sagen?", "Who can say the word 'cat flap' ten times in a row the fastest?", "0", "2", "0"),
("10", "Wer kann die meisten Tiernamen in einer Minute aufzählen?", "Who can name the most animals in one minute?", "0", "1", "0"),
("10", "Wer kann am besten einen imaginären Boxkampf vorführen?", "Who can perform an imaginary boxing match the best?", "0", "4", "0"),
("10", "Wer kann am längsten eine imaginäre Gitarre spielen?", "Who can play an imaginary guitar the longest?", "0", "3", "0"),
("10", "Wer kann am längsten einen imaginären Ball werfen und fangen?", "Who can throw and catch an imaginary ball the longest?", "0", "2", "0"),
("10", "Wer kann am besten eine berühmte Person imitieren?", "Who can imitate a famous person the best?", "0", "5", "0"),
("10", "Wer kann am meisten ohne Wörter erklären?", "Who can explain the most without using words?", "0", "4", "0"),
("10", "Wer kann am schnellsten das Wort „Rhabarber“ fünfmal hintereinander sagen?", "Who can say the word 'rhubarb' five times in a row the fastest?", "0", "2", "0"),
("10", "Wer kann am längsten auf einem Bein hüpfen?", "Who can hop on one leg the longest?", "0", "3", "0"),
("10", "Wer kann die meisten Städte in einer Minute aufzählen?", "Who can name the most cities in one minute?", "0", "1", "0"),
("10", "Wer kann am besten einen imaginären Freund vorstellen?", "Who can introduce an imaginary friend the best?", "0", "5", "0"),
("10", "Wer kann die meisten Wörter in einer Minute rückwärts sagen?", "Who can say the most words backwards in one minute?", "0", "3", "0"),
("10", "Wer kann am schnellsten das Wort „Kartoffel“ zehnmal hintereinander sagen?", "Who can say the word 'potato' ten times in a row the fastest?", "0", "2", "0"),
("10", "Wer kann am besten einen imaginären Boxkampf vorführen?", "Who can perform an imaginary boxing match the best?", "0", "4", "0"),
("10", "Wer kann am meisten lachen, ohne Geräusche zu machen?", "Who can laugh the most without making a sound?", "0", "3", "0"),
("10", "Wer kann am schnellsten das Wort „Apfel“ zehnmal hintereinander sagen?", "Who can say the word 'apple' ten times in a row the fastest?", "0", "2", "0"),
("10", "Wer kann die meisten Tiernamen in einer Minute aufzählen?", "Who can name the most animals in one minute?", "0", "1", "0"),
("10", "Wer kann die meisten Farben in einer Minute aufzählen?", "Who can name the most colors in one minute?", "0", "1", "0"),
("10", "Wer kann die meisten Städte in einer Minute aufzählen?", "Who can name the most cities in one minute?", "0", "1", "0"),
("10", "Wer kann am besten eine berühmte Filmszene nachspielen?", "Who can reenact a famous movie scene the best?", "0", "5", "0"),
("10", "Wer kann am besten eine Tierstimme nachmachen?", "Who can imitate an animal sound the best?", "0", "5", "0"),
("10", "Wer kann am längsten eine Grimasse halten?", "Who can hold a funny face the longest?", "0", "4", "0"),
("10", "Wer kann die meisten Namen von Prominenten in einer Minute nennen?", "Who can name the most celebrities in one minute?", "0", "3", "0"),
("10", "Wer kann am schnellsten das Wort „Schnell“ zehnmal hintereinander sagen?", "Who can say the word 'Fast' ten times in a row the fastest?", "0", "2", "0"),
("10", "Wer kann die meisten Wörter in einer Minute reimen?", "Who can rhyme the most words in one minute?", "0", "3", "0"),
("10", "Wer kann die meisten Wörter mit 'A' am Anfang in einer Minute nennen?", "Who can name the most words starting with 'A' in one minute?", "0", "2", "0"),
("10", "Wer kann am besten eine berühmte Persönlichkeit nachmachen?", "Who can impersonate a celebrity the best?", "0", "5", "0"),
("10", "Wer kann am schnellsten das Alphabet rückwärts aufsagen?", "Who can recite the alphabet backwards the fastest?", "0", "4", "0"),
("10", "Wer kann die meisten Wörter in einer Minute rückwärts sagen?", "Who can say the most words backwards in one minute?", "0", "3", "0"),
("10", "Wer kann am meisten ohne Wörter erklären?", "Who can explain the most without using words?", "0", "4", "0"),
("10", "Wer kann am längsten auf einer unsichtbaren Linie balancieren?", "Who can balance on an invisible line the longest?", "0", "3", "0"),
("10", "Wer kann am längsten ohne zu blinzeln starren?", "Who can stare the longest without blinking?", "0", "2", "0"),
("10", "Wer kann am besten wie ein Roboter tanzen?", "Who can dance like a robot the best?", "0", "4", "0"),
("10", "Wer kann am längsten einen imaginären Hula-Hoop-Reifen drehen?", "Who can spin an imaginary hula hoop the longest?", "0", "4", "0"),
("10", "Wer kann die meisten Korken in eine Flasche werfen?", "Who can throw the most corks into a bottle?", "0", "2", "0"),
("10", "Wer kann am längsten „lalalala“ sagen ohne Luft zu holen?", "Who can say 'lalalala' the longest without taking a breath?", "0", "3", "0"),
("10", "Wer kann am schnellsten das Wort „Rhabarber“ fünfmal hintereinander sagen?", "Who can say the word 'rhubarb' five times in a row the fastest?", "0", "2", "0"),
("10", "Wer kann die meisten Luftsprünge in 30 Sekunden machen?", "Who can do the most jumps in 30 seconds?", "0", "3", "0"),
("10", "Wer kann am längsten eine Kerze ausblasen?", "Who can blow out a candle the longest?", "0", "3", "0"),
("10", "Wer kann die meisten Namen von Automarken in einer Minute nennen?", "Who can name the most car brands in one minute?", "0", "1", "0"),
("10", "Wer kann den höchsten Turm aus Bechern bauen?", "Who can build the highest tower of cups?", "0", "2", "0"),
("10", "Wer kann die meisten Länder in einer Minute aufzählen?", "Who can name the most countries in one minute?", "0", "1", "0"),
("10", "Wer kann am längsten eine Grimasse halten?", "Who can hold a funny face the longest?", "0", "4", "0"),
("10", "Wer kann am längsten einen Ballon in der Luft halten?", "Who can keep a balloon in the air the longest?", "0", "2", "0"),
("10", "Wer kann am besten eine Geschichte erzählen?", "Who can tell the best story?", "0", "4", "0"),
("10", "Wer kann die meisten Wörter in einer Minute rückwärts sagen?", "Who can say the most words backwards in one minute?", "0", "3", "0"),
("10", "Wer kann am längsten eine Grimasse halten?", "Who can hold a funny face the longest?", "0", "4", "0"),
("10", "Wer kann am meisten lachen, ohne Geräusche zu machen?", "Who can laugh the most without making a sound?", "0", "3", "0"),
("10", "Wer kann die meisten Farben in einer Minute aufzählen?", "Who can name the most colors in one minute?", "0", "1", "0");
