INSERT INTO game_klassiker_questions (fk_pool, content, content_english, drunk_level, exposure_level, bool_drink) VALUES
("10", "#1, du musst ab jetzt jedes Mal aufstehen, wenn du etwas sagen willst.", "#1, you must stand up every time you want to say something from now on.", "0", "4", "0"),
("10", "#2, du darfst ab jetzt nur noch flüstern.", "#2, you can only whisper from now on.", "0", "2", "0"),
("10", "#1, jedes Mal wenn jemand lacht, musst du einen Schluck trinken.", "#1, every time someone laughs, you must take a sip.", "5", "3", "1"),
("10", "#2, du darfst ab jetzt keine 'ja' oder 'nein' mehr sagen.", "#2, you can't say 'yes' or 'no' from now on.", "0", "5", "0"),
("10", "#1 und #2 müssen ab jetzt die Plätze tauschen.", "#1 and #2 must switch seats from now on.", "0", "1", "0"),
("10", "#1, du darfst ab jetzt nur noch Fragen stellen.", "#1, you can only ask questions from now on.", "0", "6", "0"),
("10", "#2, du darfst ab jetzt nur noch in der dritten Person von dir sprechen.", "#2, you can only speak in the third person about yourself from now on.", "0", "5", "0"),
("10", "#1, du musst jedes Mal, wenn jemand 'trinken' sagt, einen Schluck nehmen.", "#1, you must take a sip every time someone says 'drink'.", "7", "2", "1"),
("10", "#2, du darfst ab jetzt nur noch in Reimen sprechen.", "#2, you can only speak in rhymes from now on.", "0", "7", "0"),
("10", "#1, jedes Mal wenn jemand deinen Namen sagt, musst du 'Prost' rufen.", "#1, every time someone says your name, you must shout 'Cheers'.", "4", "3", "0"),
("10", "#2, du musst ab jetzt immer, wenn jemand etwas fragt, mit einer Gegenfrage antworten.", "#2, you must always respond to a question with another question from now on.", "0", "6", "0"),
("10", "#1, du darfst ab jetzt nur noch mit deiner linken Hand trinken.", "#1, you can only drink with your left hand from now on.", "3", "2", "0"),
("10", "#2, jedes Mal wenn jemand niest, musst du einen Witz erzählen.", "#2, every time someone sneezes, you must tell a joke.", "0", "5", "0"),
("10", "#1, du darfst ab jetzt nicht mehr lachen.", "#1, you cannot laugh from now on.", "0", "4", "0"),
("10", "#2, du musst ab jetzt jedes Mal klatschen, wenn du etwas sagen willst.", "#2, you must clap every time you want to say something from now on.", "0", "3", "0"),
("10", "#1, jedes Mal wenn jemand aufsteht, musst du einen Schluck trinken.", "#1, every time someone stands up, you must take a sip.", "5", "2", "1"),
("10", "#2, du darfst ab jetzt nur noch Wörter mit mehr als 5 Buchstaben benutzen.", "#2, you can only use words with more than 5 letters from now on.", "0", "6", "0"),
("10", "#1, du musst jedes Mal, wenn jemand eine Zahl sagt, 'Bingo' rufen.", "#1, every time someone says a number, you must shout 'Bingo'.", "0", "5", "0"),
("10", "#2, du darfst ab jetzt nur noch aufstehen, wenn du etwas trinken möchtest.", "#2, you can only stand up if you want to drink from now on.", "3", "2", "0"),
("10", "#1, du darfst ab jetzt nur noch singen, wenn du etwas sagen möchtest.", "#1, you can only sing when you want to say something from now on.", "0", "8", "0"),
("10", "#2, jedes Mal wenn jemand etwas trinkt, musst du ein Kompliment machen.", "#2, every time someone drinks, you must give a compliment.", "3", "4", "0"),
("10", "#1, du darfst ab jetzt nur noch flüstern, wenn du etwas Wichtiges sagen möchtest.", "#1, you can only whisper when you want to say something important from now on.", "0", "3", "0"),
("10", "#2, du musst jedes Mal, wenn jemand lacht, 'Gute Laune!' rufen.", "#2, every time someone laughs, you must shout 'Good mood!'.", "0", "4", "0"),
("10", "#1, du darfst ab jetzt nur noch Wörter benutzen, die mit dem Buchstaben 'S' anfangen.", "#1, you can only use words that start with the letter 'S' from now on.", "0", "7", "0"),
("10", "#2, du musst ab jetzt jedes Mal aufstehen, wenn du trinken möchtest.", "#2, you must stand up every time you want to drink from now on.", "4", "2", "0"),
("10", "#1, jedes Mal wenn jemand dich anspricht, musst du in einer anderen Sprache antworten.", "#1, every time someone addresses you, you must respond in a different language.", "0", "6", "0"),
("10", "#2, du darfst ab jetzt nur noch in kurzen Sätzen sprechen.", "#2, you can only speak in short sentences from now on.", "0", "3", "0"),
("10", "#1, du musst jedes Mal, wenn jemand niest, einen Schluck trinken.", "#1, every time someone sneezes, you must take a sip.", "5", "2", "1"),
("10", "#2, du darfst ab jetzt nur noch im Stehen reden.", "#2, you can only talk while standing from now on.", "0", "3", "0"),
("10", "#1, du musst ab jetzt jedes Mal ein Tiergeräusch machen, bevor du sprichst.", "#1, you must make an animal sound before you speak from now on.", "0", "8", "0"),
("10", "#2, du darfst ab jetzt keine Adjektive mehr benutzen.", "#2, you cannot use adjectives from now on.", "0", "5", "0"),
("10", "#1, jedes Mal wenn jemand 'Hallo' sagt, musst du 'Tschüss' sagen.", "#1, every time someone says 'Hello', you must say 'Goodbye'.", "0", "4", "0"),
("10", "#2, du musst ab jetzt immer lächeln, wenn du sprichst.", "#2, you must always smile when you speak from now on.", "0", "2", "0"),
("10", "#1, du darfst ab jetzt nur noch mit geschlossenen Augen trinken.", "#1, you can only drink with your eyes closed from now on.", "4", "3", "0"),
("10", "#2, du darfst ab jetzt nur noch Wörter mit maximal 4 Buchstaben benutzen.", "#2, you can only use words with a maximum of 4 letters from now on.", "0", "6", "0"),
("10", "#1, du musst jedes Mal, wenn jemand deinen Namen sagt, einen Schluck trinken.", "#1, every time someone says your name, you must take a sip.", "6", "2", "1"),
("10", "#2, du darfst ab jetzt nur noch in der Vergangenheit sprechen.", "#2, you can only speak in the past tense from now on.", "0", "5", "0"),
("10", "#1, du darfst ab jetzt nur noch die Wahrheit sagen.", "#1, you can only tell the truth from now on.", "0", "4", "0"),
("10", "#2, du musst jedes Mal, wenn jemand lacht, einen Schluck trinken.", "#2, every time someone laughs, you must take a sip.", "7", "3", "1"),
("10", "#1, du darfst ab jetzt keine Fragen mehr beantworten.", "#1, you cannot answer questions from now on.", "0", "4", "0"),
("10", "#2, du darfst ab jetzt nur noch in der Zukunft sprechen.", "#2, you can only speak in the future tense from now on.", "0", "5", "0"),
("10", "#1, du musst jedes Mal, wenn jemand 'Danke' sagt, 'Bitte' rufen.", "#1, every time someone says 'Thank you', you must shout 'You're welcome'.", "0", "3", "0"),
("10", "#2, du darfst ab jetzt nur noch sitzen, wenn du etwas sagen möchtest.", "#2, you can only sit when you want to say something from now on.", "0", "3", "0"),
("10", "#1, du musst jedes Mal, wenn jemand aufsteht, einen Schluck trinken.", "#1, every time someone stands up, you must take a sip.", "5", "2", "1"),
("10", "#2, du darfst ab jetzt nur noch Wörter benutzen, die mit dem Buchstaben 'A' anfangen.", "#2, you can only use words that start with the letter 'A' from now on.", "0", "7", "0"),
("10", "#1, du darfst ab jetzt nur noch Floskeln verwenden.", "#1, you can only use clichés from now on.", "0", "6", "0"),
("10", "#2, du musst jedes Mal, wenn jemand niest, 'Gesundheit' rufen.", "#2, every time someone sneezes, you must shout 'Bless you'.", "0", "3", "0"),
("10", "#1, du darfst ab jetzt nur noch Wörter mit genau 3 Buchstaben benutzen.", "#1, you can only use words with exactly 3 letters from now on.", "0", "7", "0"),
("10", "#2, du darfst ab jetzt nur noch in Fragen sprechen.", "#2, you can only speak in questions from now on.", "0", "6", "0"),
("10", "#1, du musst jedes Mal, wenn jemand 'Hallo' sagt, einen Schluck trinken.", "#1, every time someone says 'Hello', you must take a sip.", "6", "3", "1"),
("10", "#2, du darfst ab jetzt nur noch Wörter mit mehr als 7 Buchstaben benutzen.", "#2, you can only use words with more than 7 letters from now on.", "0", "7", "0"),
("10", "#1, du darfst ab jetzt nur noch in vollständigen Sätzen sprechen.", "#1, you can only speak in full sentences from now on.", "0", "4", "0"),
("10", "#2, du musst jedes Mal, wenn jemand etwas trinkt, 'Prost' rufen.", "#2, every time someone drinks, you must shout 'Cheers'.", "4", "3", "0"),
("10", "#1, du darfst ab jetzt nur noch in der dritten Person von dir sprechen.", "#1, you can only speak in the third person about yourself from now on.", "0", "5", "0"),
("10", "#2, du darfst ab jetzt keine Personalpronomen mehr benutzen.", "#2, you cannot use personal pronouns from now on.", "0", "5", "0"),
("10", "#1, du musst jedes Mal, wenn jemand lacht, 'Lustig!' rufen.", "#1, every time someone laughs, you must shout 'Funny!'.", "0", "4", "0"),
("10", "#2, du darfst ab jetzt nur noch im Flüsterton sprechen.", "#2, you can only speak in a whisper from now on.", "0", "2", "0"),
("10", "#1, du darfst ab jetzt nur noch in Fremdsprachen sprechen.", "#1, you can only speak in foreign languages from now on.", "0", "6", "0"),
("10", "#2, du musst jedes Mal, wenn jemand deinen Namen sagt, 'Hallo!' rufen.", "#2, every time someone says your name, you must shout 'Hello!'.", "0", "3", "0"),
("10", "#1, du darfst ab jetzt nur noch in Zitaten sprechen.", "#1, you can only speak in quotes from now on.", "0", "7", "0"),
("10", "#2, du darfst ab jetzt nur noch im Dialekt sprechen.", "#2, you can only speak in dialect from now on.", "0", "5", "0"),
("10", "#1, du musst jedes Mal, wenn jemand niest, 'Hatschi!' rufen.", "#1, every time someone sneezes, you must shout 'Achoo!'.", "0", "3", "0"),
("10", "#2, du darfst ab jetzt nur noch im Präsens sprechen.", "#2, you can only speak in the present tense from now on.", "0", "4", "0"),
("10", "#1, du darfst ab jetzt nur noch in der Vergangenheitsform sprechen.", "#1, you can only speak in the past tense from now on.", "0", "5", "0"),
("10", "#2, du musst jedes Mal, wenn jemand aufsteht, 'Auf Wiedersehen' rufen.", "#2, every time someone stands up, you must shout 'Goodbye'.", "0", "4", "0"),
("10", "#1, du darfst ab jetzt nur noch auf Englisch sprechen.", "#1, you can only speak in English from now on.", "0", "3", "0"),
("10", "#2, du musst jedes Mal, wenn jemand 'bitte' sagt, 'danke' rufen.", "#2, every time someone says 'please', you must shout 'thank you'.", "0", "3", "0"),
("10", "#1, du darfst ab jetzt nur noch in Fremdsprachen sprechen.", "#1, you can only speak in foreign languages from now on.", "0", "6", "0"),
("10", "#2, du darfst ab jetzt nur noch mit geschlossenen Augen reden.", "#2, you can only speak with your eyes closed from now on.", "0", "5", "0"),
("10", "#1, du musst jedes Mal, wenn jemand niest, 'Hatschi!' rufen.", "#1, every time someone sneezes, you must shout 'Achoo!'.", "0", "3", "0"),
("10", "#2, du darfst ab jetzt nur noch im Präsens sprechen.", "#2, you can only speak in the present tense from now on.", "0", "4", "0"),
("10", "#1, du darfst ab jetzt nur noch in der Vergangenheitsform sprechen.", "#1, you can only speak in the past tense from now on.", "0", "5", "0"),
("10", "#2, du musst jedes Mal, wenn jemand aufsteht, 'Auf Wiedersehen' rufen.", "#2, every time someone stands up, you must shout 'Goodbye'.", "0", "4", "0"),
("10", "#1, du darfst ab jetzt nur noch auf Englisch sprechen.", "#1, you can only speak in English from now on.", "0", "3", "0"),
("10", "#2, du musst jedes Mal, wenn jemand 'bitte' sagt, 'danke' rufen.", "#2, every time someone says 'please', you must shout 'thank you'.", "0", "3", "0"),
("10", "#1, du darfst ab jetzt nur noch in Zitaten sprechen.", "#1, you can only speak in quotes from now on.", "0", "7", "0"),
("10", "#2, du darfst ab jetzt nur noch im Dialekt sprechen.", "#2, you can only speak in dialect from now on.", "0", "5", "0"),
("10", "#1, du musst jedes Mal, wenn jemand niest, 'Hatschi!' rufen.", "#1, every time someone sneezes, you must shout 'Achoo!'.", "0", "3", "0"),
("10", "#2, du darfst ab jetzt nur noch im Präsens sprechen.", "#2, you can only speak in the present tense from now on.", "0", "4", "0"),
("10", "#1, du darfst ab jetzt nur noch in der Vergangenheitsform sprechen.", "#1, you can only speak in the past tense from now on.", "0", "5", "0"),
("10", "#2, du musst jedes Mal, wenn jemand aufsteht, 'Auf Wiedersehen' rufen.", "#2, every time someone stands up, you must shout 'Goodbye'.", "0", "4", "0"),
("10", "#1, du darfst ab jetzt nur noch auf Englisch sprechen.", "#1, you can only speak in English from now on.", "0", "3", "0"),
("10", "#2, du musst jedes Mal, wenn jemand 'bitte' sagt, 'danke' rufen.", "#2, every time someone says 'please', you must shout 'thank you'.", "0", "3", "0"),
("10", "#1, du darfst ab jetzt nur noch in Zitaten sprechen.", "#1, you can only speak in quotes from now on.", "0", "7", "0"),
("10", "#2, du darfst ab jetzt nur noch im Dialekt sprechen.", "#2, you can only speak in dialect from now on.", "0", "5", "0"),
("10", "#1, du musst jedes Mal, wenn jemand niest, 'Hatschi!' rufen.", "#1, every time someone sneezes, you must shout 'Achoo!'.", "0", "3", "0"),
("10", "#2, du darfst ab jetzt nur noch im Präsens sprechen.", "#2, you can only speak in the present tense from now on.", "0", "4", "0"),
("10", "#1, du darfst ab jetzt nur noch in der Vergangenheitsform sprechen.", "#1, you can only speak in the past tense from now on.", "0", "5", "0"),
("10", "#2, du musst jedes Mal, wenn jemand aufsteht, 'Auf Wiedersehen' rufen.", "#2, every time someone stands up, you must shout 'Goodbye'.", "0", "4", "0"),
("10", "#1, du darfst ab jetzt nur noch auf Englisch sprechen.", "#1, you can only speak in English from now on.", "0", "3", "0"),
("10", "#2, du musst jedes Mal, wenn jemand 'bitte' sagt, 'danke' rufen.", "#2, every time someone says 'please', you must shout 'thank you'.", "0", "3", "0"),
("10", "#1, du darfst ab jetzt nur noch in Zitaten sprechen.", "#1, you can only speak in quotes from now on.", "0", "7", "0"),
("10", "#2, du darfst ab jetzt nur noch im Dialekt sprechen.", "#2, you can only speak in dialect from now on.", "0", "5", "0");
